Week1 [Step 2] Molly
yagom-academy/swift_starter-week1 pull request #104
Opened 2022-04-19 18:50 UTC by iam-molly

@ye-ha 
# 궁금한 점
# 주제
- 제가 쓴 코드가 너무 단순한 느낌이 드는데 괜찮나요?

2022-04-21 00:00 UTC, ye-ha requested changes
반복문을 사용하셨고, 함수 분리하신 점 아주 좋습니다! 👍
컨벤션 수정해주시면 머지하겠습니다. 

순서도에서 함수를 정의한다는 표현을 사용해주셨어요. 이 부분이 코드와 관련된 부분이라서 다음 스텝 순서도에서는 함수 안에 내용, 어떤 순서에 어떤 기능을 하는지 설명해주면 좋겠어요.

몰리님이 주신 질문이 코드가 몇 줄 없는데 문제될게 없는지 여쭤봐주신 걸까요? 
아니면 다른 뜻이 있을까요? 궁금합니다. 👀

2022-04-21 12:24 UTC, iam-molly commented on CodeStarterCamp_Week1/main.swift
> +
아이스크림 그리는 코드를 두 가지 방법으로 만들어서, 위에 것과 아래 것을 구분하려고 그랬던 것 같아요.

2022-04-21 12:27 UTC, iam-molly commented on CodeStarterCamp_Week1/main.swift
> +
의도한 건 아닌데 왜 저렇게 했었는지 모르겠네요😅

2022-04-21 12:34 UTC, iam-molly commented
사실 처음에는 아이스크림을 그리는 별도 반복문을 사용해서 나타내려다가 실패해서 지금의 코드를 쓴거였거든요! 그러다보니 처음에 시도했던 코드에 비해 실제로 작성한 결과물이 넘 단순해보여서 이런 질문을 드렸던 것 같아요!

2022-04-22 00:35 UTC, ye-ha commented
그리려고 하는 내용을 잘 그리고 있기 때문에 단순하다고 생각하지 않습니다 😄

2022-04-22 03:19 UTC, merged