week1 Step2 파일추가
yagom-academy/swift_starter-week1 pull request #112
Opened 2022-04-21 07:11 UTC by limdumb

아이스크림 파일 추가 했습니다 :) 꼼꼼하게 봐주셔서 감사합니다 !!

2022-04-21 07:13 UTC, Kioding commented
@limdumb 
담당 학습도우미를 태그하지 않으면 확인할 수 없답니다 😭😭
꼭 본인 학습도우미를 글 수정을 통해 태그해주세요!

2022-04-22 07:55 UTC, leeari95 requested changes
임덤덤님 안녕하세요~
스텝2를 진행하시느라 고생많으셨습니다!

일단 제가 말씀드리는 의견들은 대부분 정말 궁금해서 여쭤보는 것이니 
무조건 잘못된 것이다 라고 판단하지 않으셨으면 좋겠습니다.
제 말이 다 정답인 것도 아니니 꼭 참고해주세요. 😉

---

> ### 일단 코드를 실행해보았는데, 막대기 부분이 예시와 다른 것 같아요.

<img width="367" alt="image" src="https://user-images.githubusercontent.com/75905803/164637402-8c584fa4-848b-400f-ae12-4c0c0776291b.png">

* 이 부분은 수정이 필요할 것 같습니다.

#

> ### 기능을 분리하여 함수 2개를 만들라고 되어있는데요.

* 코드를 보니 함수 외에 반복문을 사용하셔서 함수를 실행하시는 형태가 보여지고 있는데요.
* 이 부분을 기능 단위로 다시한번 고민해보시고 함수로 재작성 해보셨으면 좋겠습니다.

#

> ### 네이밍이 명확하지 않은 것 같습니다.

* 네이밍은 간결한 것도 중요하지만 더 중요한 것은 명확함입니다. 
* [Swift - API Design Guidelines](https://www.swift.org/documentation/api-design-guidelines/)를 다시 확인해볼까요?

#

> ### 함수에 반환타입으로 String을 정의해주신 이유가 궁금합니다.

이미 `ice`나 `underStic`함수 내부에서 print 함수를 통해 문자열을 출력하고 있는 형태로 보여지는데요.
다시 한번 함수 아래에서 for문을 활용하여 print를 한번 더 하고 있는 것 같습니다.
어떤 이유로 작성하신건지 다시한번 고민해보셨으면 좋겠습니다.

#

코멘트에 대한 의문점이나 궁금한점, 어려운점은 DM 편하게 주시면 되겠습니다.
고생 많으셨습니다~ 😆

2022-04-22 07:55 UTC, leeari95 commented on CodeStarterCamp_Week1/main.swift
> +var stic: String = "|"
이 문자열들을 따로 선언해주신 이유가 궁금합니다.
또 왜 변수인지 이유를 알 수 있을까요? 🤔

2022-04-22 07:55 UTC, leeari95 commented on CodeStarterCamp_Week1/main.swift
> +func ice(x: String) -> String {
함수명을 다시 고민해볼까요?
이 함수는 어떤 기능을 하는지 생각해보고 네이밍을 다시 해봅시다!

2022-04-22 07:55 UTC, leeari95 commented on CodeStarterCamp_Week1/main.swift
> +}
왜 이 for문은 함수 밖으로 나와있는 걸까요?
요구사항을 다시한번 살펴보면 좋을 것 같습니다!

> - 전체 아이스크림을 그리는 함수 두 개를 만들어봅시다.
    - 아이스크림 부분을 그리는 함수
    - 막대기(손잡이) 부분을 그리는 함수

2022-04-22 07:55 UTC, leeari95 commented on CodeStarterCamp_Week1/main.swift
> +    return ""
print 후 빈 문자열을 반환하는 이유가 무엇인가요?

2022-04-22 07:55 UTC, leeari95 commented on CodeStarterCamp_Week1/main.swift
> +    return ""
이 함수도 빈문자열을 반환하고 있는데... 어떤 의미인가요?

2022-04-22 07:55 UTC, leeari95 commented on CodeStarterCamp_Week1/main.swift
> +func underStic(x: String) -> String {
이 함수명도 기능에 맞춰 다시 네이밍을 해볼까요?
파라미터 이름도 `x`인데 어떤 것을 의미하는지 모르겠어요!

2022-04-22 07:55 UTC, leeari95 commented on CodeStarterCamp_Week1/main.swift
> +}
이 for문도 마찬가지로 함수 밖에서 실행되고 있는 형태네요.
요구사항에 맞춰 아이스크림과 막대기를 그리는 함수 2개로 나누어볼 순 없을까요?

2022-04-22 07:58 UTC, leeari95 commented
그리고 PR 제목이 잘못되어있는 것 같네요.
`Week3`를 `Week1` 로 수정해주셔야할 것 같습니다!

2022-04-23 02:05 UTC, limdumb commented
@leeari95 IceCream 파일 수정 했습니다 :).. 확인 한번 부탁 드리겠습니다 ㅠ-ㅠ

2022-04-25 07:38 UTC, limdumb commented
@leeari95 순서도 및 main파일로 변경 하였습니다 :) 확인 부탁 드립니다..!

2022-04-25 07:52 UTC, limdumb commented on CodeStarterCamp_Week1/main.swift
> +var stic: String = "|"
문자열을 따로 선언 한건 함수의 매개변수나 함수안에 그때그때 타이핑해서 넣기보단 선언후에 편하게 넣는게 좋겠다 싶어서 선언 해둔것이고 변수인건 단순 선언을 하기위해서 변수를 썼었던거 같습니다 :(

2022-04-25 07:52 UTC, limdumb commented on CodeStarterCamp_Week1/main.swift
> +    return ""
위에 함수들을 출력했을때 () <- 빈 괄호가 게속출력이 되어서 return 값으로 "" 빈상태를 주면 없어지지않을까 싶어서 넣어봤었습니다!

2022-04-25 08:12 UTC, limdumb commented on CodeStarterCamp_Week1/main.swift
> +    return ""
위와 같은 의미로 return값을 줘봤습니다!

2022-04-25 09:34 UTC, leeari95 commented on CodeStarterCamp_Week1/main.swift
> +var stic: String = "|"
변수 선언시 let으로 상수로 선언하는 습관을 들여볼까요?
개발자는 의도되지 않은 변경에 꼭 주의해야 합니다. 😁

2022-04-25 09:35 UTC, leeari95 commented on CodeStarterCamp_Week1/main.swift
> +    return ""
단순 print를 하는 경우에는 반환값이 꼭 필요할까? 하는 의문이 들어서 질문을 드렸던 것이였어요. 😊
빈괄호`()`의 경우는 어떤 타입인지도 알아보면 좋을 것 같습니다.

2022-04-25 09:42 UTC, leeari95 approved these changes
수정사항 잘 확인했습니다~
이전보다 훨씬 코드 가독성이 좋아진 것 같네요. 👍🏻👍🏻 

그리고 한가지 말씀드리자면 제 의견이 무조건 정답은 아니니 꼭 참고해주세요.
피드백도 뭔가 이해가 되지 않거나, 의문이 생긴다거나 하는 점이 있다면
그때마다 답변이나 DM을 주셔도 좋을 것 같습니다.
코드리뷰는 코드를 점검하는 시간이기도 하지만 서로 소통하는 시간이기도 합니다!
이 점을 꼭 참고해주셨으면 좋겠습니다~

제 의견 반영해주셔서 너무너무 감사드려요.
코드도, 순서도도 더이상 큰 문제없는 것 같아 Merge 해드리겠습니다.
다음 스텝에서 뵐게요. 화이팅!!!! 💪🏻

#

> 순서도가 살짝 수정이 필요해보여요!

<img width="574" alt="image" src="https://user-images.githubusercontent.com/75905803/165063625-26cb47dd-42d8-4565-bf70-5e87253869cb.png">

2022-04-25 09:42 UTC, merged