Week 1 [Step 3] OneE
yagom-academy/swift_starter-week1 pull request #115
Opened 2022-04-22 08:00 UTC by One-E12

@jaemuYeo 

오랜만이에요 잼킹 :) 드디어 시험이 끝나서 PR을 보내게 되었답니다! 

---

일단 command line Tool 내부에 새로운 파일을 생성하라고 하셨는데 저는 프로젝트를 생성했어요...!
저번에 다른 분이 디스코드방에 올려주신 질문과 같은 궁금증이었는데, 잼킹이 step2 에서 한 것과 똑같이 하면 된다는 답변을 주신 걸 보고 
똑같이 프로젝트를 만들었는데, 이렇게 프로젝트를 만드는 걸 command line Tool 내부에 새로운 파일을 생성하라고 하는걸까요? 🤔
새로운 파일을 생성하라는 말을 봤을 땐 사실 main밑에 하나의 파일을 더 만들면 되는게 아닐까? 하는 생각이 들었거든요. 
처음에 그렇게 시도해봤지만, main에 있는 친구와 함께 돌아가거나 오류가 발생하더라구요! 그래서 main을 기준으로 돌아가는구나! 하는 깨달음을 얻긴 했는데..., 매번 이렇게 새로운 프로젝트를 만들어서 하는건가? 하는 궁금증이 생겼습니다. 🧐

----

변수를 설정해줄 때 저는 프로젝트 가장 상단에서 설정해줬는데, 문득 그런 의문이 들었어요. 
각 함수가 돌아갈 때, 이 변수가 처음에 어떻게 설정되어있는지 꼭 위로 올라가서 확인해야할까? 하는 생각이요.
그래서 함수를 구현하는 코드 위에 변수를 설정해주는 것이 좋은지, 아니면 지금 설정한 것 처럼 가장 상단에서 설정해줘야하는게 좋은지 궁금해졌습니다. 혹시 관련된 내용이 [여기](https://docs.swift.org/swift-book/)에 나와있을까요...? 
혹시 그렇다면 예/ 아니오로 대답해주세요 잼킹! 제가 하나씩 읽어보고 찾아볼게요!! 
혹시 몰라서 구글에 좋은 변수 설정 위치라고 검색을 해봤는데, 아직 마땅한 답을 찾지는 못했습니다 😢 다들 변수를 한 번에 알아보기 쉽게 작성하라는 이야기만 해주더라구요. 

--- 

순서도에 대한 고민인데요. 
아직도 순서도는 익숙하지 않지만, 그래도 이제는 조금 자신감이 생긴 것 같아요. 🐥
하나 궁금했던 건, makepeperoBar의 순서도 같은 경우, 사실 peperoBarlength만 바뀌고 나머지 설정은 바뀌지 않는데
이런 경우에도 순서도를 빼빼로 하나 만들 때 마다 작성해주는게 좋은가요? 
아니면 그냥 하나의 순서도로 첨부해주는것이 좋은가요? 

--- 

1번 순서도 
<img width="402" alt="normalpepero" src="https://user-images.githubusercontent.com/97447840/164644229-a3b1ca46-6cd8-46db-bce6-042318a3c30d.png">

2번 빼빼로 순서도 
<img width="537" alt="topping no1" src="https://user-images.githubusercontent.com/97447840/164644297-451f6d8d-d97d-4a84-a1e3-37dccda4bf0f.png">

3번 빼빼로 순서도 

<img width="417" alt="topping no2" src="https://user-images.githubusercontent.com/97447840/164644340-1396f694-b640-40d8-8127-37fb2adc26f1.png">

4번 빼빼로 순서도 
<img width="417" alt="Nudepepero" src="https://user-images.githubusercontent.com/97447840/164644396-f8a0f753-c902-459a-94d2-1b9971cec41a.png">

2022-04-23 15:42 UTC, jaemuYeo requested changes
안녕하세요 원이!! 스텝3를 하면서 고민을 엄청 한게 코드에 녹았네요!!
정말정말 고생 하셨습니다 👍
시험은 잘 보셨나요!! 시험도 끝났으니 코딩에 더 불내셔야죠! ㅎㅎ 🔥
일단 코드에 대한 의견을 먼저 말씀드리겠습니다!
불필요한 개행과 swift 스타일 컨벤션이 지켜지지 않은 부분이 보여요~
해당 문법을 사용할 때 공식문서에서 어떻게 띄어쓰기가 되어있고,
줄바꿈은 어떻게 처리했는지 확인해보고 작성해 나가시는 방법을 추천드립니다!!
초반에만 습관을 들이면 앞으로는 안보고도 금방 하실거예요 😉
다음은 남겨주신 질문에 대한 답변 남기겠습니다!

---

1. 프로젝트 파일 생성 문제
음,, 저의 생각은 새로운 프로젝트를 생성하는 것이 아닌 하나의 프로젝트에 새로운 command line Tool파일을 생성해서 작성하는 것이었어요!
빼빼로 프로젝트를 실행할때에 main의 파일을 잠시 주석처리 해주신 후 실행해보시는 건 어떨까요?
그리고 어떤 에러가 발생하는지에 대해도 남겨주시면 좋을 거 같아요!

---

2. 코드를 작성하면서 중요한 것들중 하나가 `가독성`이라고 생각합니다.
지금은 100줄도 안되는 코드를 작성하고 있지만
1000줄, 10000줄이 되는 코드에서 함수 사이사이에 변수들이 껴있다고 가정하면
원이는 어떠실것 같나요?? 한번 상상해보세요 !! 😫
가독성을 지키는 방법에는 변수 선언 위치, 줄바꿈, 띄어쓰기, 네이밍 등등이 있습니다!

3. 순서도
이 부분이 어려울 수 있는데 코드를 다시 한번 작성해 보도록 할까요?
각각의 기능에 따른 함수 ( Step3 Todo부분을 읽어보시면 4개 정도의 함수)를 구현하라고
나와있어요!
하나의 함수 호출만으로 매개변수에 값을 입력받아 
다양한 빼빼로를 출력할 수 있게 구현해보셔요!
그 후 순서도를 한 번 더 수정해주시면 좋을 것 같아요 😀

2022-04-23 15:42 UTC, jaemuYeo commented on CodeStarterCamp_Week1/makePepero/makePepero/main.swift
> +
불필요한 줄바꿈이 3줄이나 있군요!

2022-04-23 15:42 UTC, jaemuYeo commented on CodeStarterCamp_Week1/makePepero/makePepero/main.swift
> +
줄바꿈을 안하는게 좋을 것 같아요! 아래의 줄바꿈문제는 `줄바꿈`으로 코멘트 해드릴게요!

2022-04-23 15:42 UTC, jaemuYeo commented on CodeStarterCamp_Week1/makePepero/makePepero/main.swift
> +
줄바꿈

2022-04-23 15:42 UTC, jaemuYeo commented on CodeStarterCamp_Week1/makePepero/makePepero/main.swift
> +makeNormalPepero(peperobodylength: 10)
줄바꿈 한번 필요

2022-04-23 15:42 UTC, jaemuYeo commented on CodeStarterCamp_Week1/makePepero/makePepero/main.swift
> +
줄바꿈

2022-04-23 15:42 UTC, jaemuYeo commented on CodeStarterCamp_Week1/makePepero/makePepero/main.swift
> +        else {
공식문서에서 if-else에서 else의 위치가 어디인지 한번  확인해주세요!☺️

2022-04-23 15:42 UTC, jaemuYeo commented on CodeStarterCamp_Week1/makePepero/makePepero/main.swift
> +
줄바꿈

2022-04-23 15:42 UTC, jaemuYeo commented on CodeStarterCamp_Week1/makePepero/makePepero/main.swift
> +
줄바꿈

2022-04-23 15:42 UTC, jaemuYeo commented on CodeStarterCamp_Week1/makePepero/makePepero/main.swift
> +        else {
이 곳의 else 위치도 확인해주세요!

2022-04-24 09:19 UTC, One-E12 commented
코드 수정 후 다시 작성해서 보내요 잼킹 :) 

--- 

기존에 새로 만든 프로젝트는 삭제했고, 잼킹이 말씀해주신 것 처럼 새로운 파일을 만들어서 돌려보니, 
statements are not allowed at top level 이 나왔습니다.
구글링을 해본 결과, 모든 파일에 최상위 코드가 있으면 프로그램 시작 위치를 결정하는 것이 어렵다는 글을 읽었어요.

 이 글을, 제가 제 생각대로 다시 이해해본 건 스위프트의 프로그램은 main을 가장 위의 파일로 인식하고 돌아가는데, 새로운 파일을 만들어버리면 가장 위의 파일로 인식되는 것들이 꼬여버려서 실행되지 않게 되는거죠. 
그래서 기존에 main 즉, 가장 우선으로 실행시켜줘야 하는 친구들의 이름을 바꿔서 이들의 순서를 뒤로 미뤄주고, 
지금 당장 실행시킬 내용을 담은 친구들을 main이라는 이름으로 바꿔, 실행시켜줘야한다고 이해했어요. 

맞게 이해했는지는 모르겠지만요. 🤔🧐
참고한 자료는 [블로그](https://zeddios.tistory.com/69), [공식문서](https://developer.apple.com/swift/blog/?id=7) 이렇게 두가지 였습니다. 

---

여전히 띄어쓰기에 대한 문제는 ... 해결되지 않는군요...! 아직 익숙하지 않아서 더 그런가봐요.😢
잼킹이 이전에 링크해주신 문서들을 다시 읽어봤는데도 아직 어려운건 제가 아직 저의 것으로 학습하지 못했기 때문이겠죠?😢 
그래도 하나 하나 제가 쓴 코드들과 비슷한 내용들을 찾아서 읽어보도록 할게요.! 
이번에는 제대로 수정했기를...🙏

---

그리고 다시 작성해보다가 문득 궁금해진 내용인데요. 
함수와 메서드에 대한 개념을 잘 모르겠더라구요. 
메서드는 클래스,구조체, 열거형에 속하는 함수고 함수는 클래스, 구조체, 열거형과 무관하고 재사용이 가능한 코드뭉치라고 하더라구요.

그럼 제가 작성한 코드 중 마지막 makePersonalpepero에서 3가지 메서드를 호출하는 함수라면... 
```swift
class pepero { 
      var peperoBodylength: Int = 0
} 
```
형식을 사용해서 빼빼로 바나 몸통을 구성하는 함수를 작성해야했던건지 궁금합니다. 

---

순서도 다시 작성해봤는데, 위의 질문과 연결해서 만약 class를 사용한다면 다시  작성해올게요...! 🧐
1. 빼빼로 만들기 함수 < 빼빼로 바, 빼빼로 토핑, 빼빼로 기본>
<img width="717" alt="빼빼로 만들기 함수" src="https://user-images.githubusercontent.com/97447840/164969350-151fb1a8-4693-4f38-8ab5-a2590d0b94e2.png">

2. 빼빼로 호출하는 함수 
<img width="746" alt="빼빼로 호출하기 함수" src="https://user-images.githubusercontent.com/97447840/164969377-09a26afa-1a80-4aae-9244-4b2fd94b7297.png">

---

주말인데도 답변 주셔서 감사해요 잼킹 :)

2022-04-25 15:24 UTC, jaemuYeo requested changes
원이 코드가 정말 많이 개선되었어요!! 감탄했습니다 👏
질문주신 첫번째 파일 생성에 대한 문제도 잘 해결하신거 같아요!!
코드 작성뿐만 아니라 이러한 해결 문제능력도 한단계 성장하신 거예요👍
띄어쓰기나 줄바꿈등에 대한 부분은 많이 해봐야해요~
지금 너무나 잘하고 계세요!!
저도 더 신경써서 코멘트에 남겨놓을테니 수정 후에 꼭 몇 번씩이고 
원이가 작성하신 코드를 보기를 바라요~

세 번째 질문 주신 메서드와 함수에 대한 궁금증에 대해서 답변 드릴게요!
예를들어 이번 프로젝트에서 빼빼로만들다()라는 함수를 만들었어요! 말그대로 함수겠죠?
이 함수가
```swift
class 과자공장 {
     func 빼빼로만들다() {

     }
}
```
과자공장이라는 클래스 안에 들어가면 과자공장의 메서드가 되는거랍니다!
객체안에서의 프로퍼티(변수, 상수)는 객체의 상태가 되고,
메서드(함수)는 객체가 할 수 있는 행동(다른 객체와 메시지를 주고받는 무언가)라고 생각해주시면 됩니다!
이번 프로젝트에서는 class를 사용하실 필요 없어요~ 
다음 프로젝트에서 기다리고 있으니 지금 사용하시는건 `함수`라고 생각하시고
이어나가주세요~
순서도는 기본, 토핑, 누드 상관없이 하나로 통합해도 좋아요☺️

2022-04-25 15:24 UTC, jaemuYeo commented on CodeStarterCamp_Week1/main.swift
> +        for _ in 1...2 {
여기에 2는 어떤것을 의미할까요?
peperoBarLength는 빼빼로의 바 길이만큼이라는 범위라는 것을 알겠는데
2와 같이 어떤것을 의미하는지 애매한 숫자를 `매직넘버`라고 불러요
검색을 통해 매직넘버가 무엇인지 어떻게 해결할 수 있을지 한번 알아보시길 바라요!😉
너무 오래 고민하지마시고 잘 모르시겠으면 바로 디엠주세요!

2022-04-25 15:24 UTC, jaemuYeo commented on CodeStarterCamp_Week1/main.swift
> +func makePeperoBar(peperoBarlength: Int) {
함수명에 peperoBar라는 단어가 있는데 매개변수에도 peperoBar라는 네이밍이 있어요!
보통 함수는 한 문장처럼 읽히게 네이밍하라고들 하는데
지금 작성한 함수를 해석하면 똑같은 말이 두 번 나오지 않을까요??
아래 몇몇 함수 포함입니다!

2022-04-25 15:24 UTC, jaemuYeo commented on CodeStarterCamp_Week1/main.swift
> +    for _ in 1...peperoBodylength/2 {
peperoBodyLength / 2라는 수식을 하나의 단어로 추려내어 변수 또는 상수로 만든 후 넣는게 좋을 거 같아요 ☺️
그리고 swift에서 연산자를 사용할 때 띄어쓰기를 어떻게 하는지도 한 번 더 체크해주세요!

2022-04-25 15:24 UTC, jaemuYeo commented on CodeStarterCamp_Week1/main.swift
불필요한 줄바꿈이 있군요!

2022-04-25 15:24 UTC, jaemuYeo commented on CodeStarterCamp_Week1/main.swift
> +func makeNormalPepero(peperoBodylength: Int, peperoBody: String) {
두 함수가 줄바꿈 없이 붙어있어요! 다른 곳과 비교해볼까요?
코드는 통일 된 모습이 매우 중요합니다!

2022-04-25 15:24 UTC, jaemuYeo commented on CodeStarterCamp_Week1/main.swift
> +        print(" " + peperoBody)
빼뺴로몸통과 한칸 띄어쓰기된 문자열을 더하고 있는데 저 문자열도 무언가 의미가 있었으면 해요!
매직넘버와 같은 의미라 생각해주세요😊

2022-04-25 15:24 UTC, jaemuYeo commented on CodeStarterCamp_Week1/main.swift
> +    print("<정보>")
지금 다섯 번의 프린트 함수를 통해 정보들을 출력하고 있는데
프린트 함수 하나에 다섯 줄을 표현할 수 있는 방법이 있답니다!
한 번 그렇게 바꿔보실 수 있을까요??
가능하다면 이 프린트되는 함수도 또다른 하나의 함수로 기능분리 해주면 멋질 거 같아요!☺️

2022-04-25 15:24 UTC, jaemuYeo commented on CodeStarterCamp_Week1/main.swift
> +    if peperoTopping == "" {
이 곳의 빈 문자열도 무언가 의미가 있었으면 해요!

2022-04-25 16:49 UTC, One-E12 commented
잼킹의 리뷰를 보고 변수 이름이랑 이런 저런걸 다 수정해봤답니다...! 
근데 문득 제 코드를 보는데 너무... 변수 이름이 길다는 생각이 들었어요.
쭉 읽어보는데 너무 지저분해보이는 기분이 막 들더라구요. 

변수나 함수의 이름을 지을 때 명확하게 하기 위해서 최대한 알아보기 쉽게 적어본건데...
그냥 쭉 훑어보니까 어우..., 너무 길더라구요. 만약 수정을 한다면 더 짧게 만드는게 가능할까요? 🤔 
일단 제가 조금 고민을 해본 내용은, 
 1. 함수를 makePepero라고 해버리면 토핑인지 노말인지 잘 모르니까 모호한 함수 이름이 될 것 같다는 생각이 들었어요.
2. 변수들을 위에 다 선언해서 하단에 함수를 만들 때 간단하게 만드는건데 🤔
변수를 상단에 다 선언해서 함수를 만들 때 간단하게 쓴다고 해도, 계속 저 변수 이름들을 쓸 것 같다는 생각이 들었어요.
그렇다고 x, y, z 를 만들어서 z = bodylength 이렇게 하기엔 읽을 수 있는? 글을 읽듯 읽히는 함수가 될 것 같지 않더라구요! 
그럼 보기엔 깔끔하지만 가독성이 없을 거라는 결론에 도달했답니다.😞

이럴 땐 그냥 저렇게 길게 쭈우욱 써주는게 좋을까요? 🤔 

---

그리고 지금 반복되는 숫자를 설정해줘서 peperoBarLoopNum이라고 이름을 지었는데 
더 간단한 이름이 있을까요?

이름 짓기 굉장히 힘드네요

--- 

아, 그리고 매직 넘버는 검색해서 해결해봤어요! 
- 매직넘버란? : 소스 안에 구체화 된 수치를 의미한다. 
   매직넘버를 지양하는 이유는, 만약 구체화 된 수치를 바꾸게 되는 경우 해당 수치가 적용되는 모든 구간을 찾아서 수정해줘야하는데, 이 때 잘못된 수정이 발생될 수도 있기 때문이다. 
   즉, 재사용성을 높이고 부작용을 피하기 위해 지양해야하는 것! 
-> 그럼 어떻게 사용하는 것이 좋은가? : 상징적인 정수로 치환해서 사용하는 것이 좋다!

라는 결론이 나와서 해결해봤는데 옳은 해결로 도달했는지는 ... 잘 모르겠지만!
그래도 2라는 구체적인 수치보다는 조금 더 괜찮아진 것 같다는 결론입니다! 

잼킹의 생각은 어떠신가요?!

2022-04-26 07:33 UTC, jaemuYeo requested changes
정말 빠르게 수정하셨군요 👍
질문에 대한 답변 남기고 마지막으로 한 번만 더 수정후 머지진행할게요!

네이밍의 길이에 대해 고민하셨군요
[공식문서](https://www.swift.org/documentation/api-design-guidelines/)의 네이밍 첫 줄에
뭐라고 적혀있는지 한 번 확인해주세요!!
너무 긴 네이밍도 가독성 측면에 좋지않지만 너무 추려낸 네이밍도 단점이 될 수 있을 것 같아요!
지금 코드에서는 전혀 길어보이는 코드가 보이지 않네요!!

1. makePepero라는 함수명만으로 빼빼로를 만들 수 있다면 
이번 스텝에서의 목표는 이뤘다 생각합니다!
함수의 매개변수에서 문자열들로 모양을 작성하여 충분히 어떤 빼빼로인지 표현이 되는 것 같은데
어떻게 생각하시나요??
만약 토핑인지 노말인지를 프린트를 통해 나타내고싶으면 무언가의 기능을 또 추가해도 좋겠죠??

2. 이 부분은 코드 코멘트에 남겨놓은 것만으로 해결이 됐을까요?
추가적으로 궁금하시면 언제든 디엠주세요!!

`peperoBarLoopNum ` 네이밍에 대한 부분도 코드에 남겨놓았습니다!
매직넘버에 대해 알아보셨군요!!
지금 결과물이 더 좋다고 저도 생각은 들지만 몇몇 네이밍만 조금 더 고쳐보시면 좋을거 같아요 ☺️

2022-04-26 07:33 UTC, jaemuYeo commented on CodeStarterCamp_Week1/main.swift
> +var peperoShapeLoopNum: Int = 2
이 곳에 작성된 전역 변수 중 하나의 함수에만 쓰이는 것들이 있군요!
함수 내부에 지역변수로 생성해서 사용하는 것이 좋아보여요 ~

2022-04-26 07:33 UTC, jaemuYeo commented on CodeStarterCamp_Week1/main.swift
> +        for _ in 1...peperoShapeLoopNum {
길이를 구하기 전에 너비를 구하고 있죠? 
길이를 length로 했으니 내부 for문은 너비로 해주면 좋을 거같아요!
원이 생각은요??

2022-04-26 07:33 UTC, jaemuYeo commented on CodeStarterCamp_Week1/main.swift
> +    let toppingPeperoLength: Int = bodyLength / 2
상수와 for문 사이에 줄바꿈 한 번 해주면 좋을 거같아요 ☺️

2022-04-26 07:33 UTC, jaemuYeo commented on CodeStarterCamp_Week1/main.swift
> +    print("""
프린트 문 내부의 문자열 값들이 들여쓰기가 되어있지 않군요!
공식문서에서 이런 형태를 어떻게 들여쓰기해서 사용하는지 한 번 더 체크해주세요!😉

2022-04-26 07:33 UTC, jaemuYeo commented on CodeStarterCamp_Week1/main.swift
> +    peperoInfo(bodyLength: bodyLength, bodyShape: bodyShape, toppingShape: toppingShape, barLength: barLength)
함수의 실행부와 if문 사이에 한번 개행이 있었으면 좋겠어요 ☺️

2022-04-26 15:04 UTC, One-E12 commented
:) 수정해서 다시 PR보내요 잼킹!_!

짧은 고민을 했는데 """ 을 구별해서 써주는게 본문이 어떤건지 알 수 있을 것 같아요! 
그래서 이렇게 수정해봤답니다!

2022-04-26 16:17 UTC, jaemuYeo reviewed
스텝3 고생많으셨습니다!!
마지막으로 전에 남긴 전역변수에 대한 부분도 한번 고민해보시고,
정보와 빼빼로가 그려지는 사이에 한번의 줄바꿈이 되게 구현해보시는 것도 좋을거같아요🙂
```swift
func peperoInfo(bodyLength: Int, bodyShape: String, toppingShape: String, barLength: Int) {
    print("""
    <정보>
    길이: \(bodyLength)
    몸통: \(bodyShape)
    토핑: \(toppingShape)
    막대 길이: \(barLength)
    """)
}
```
아까 얘기 나눴던 부분은 다시 확인해보니
이렇게 작성해야 콘솔에 프린트 될때 정상으로 표현될 거 같습니다!
이번 프로젝트 머지 진행할게요! Week2에서 만나요 ☺️👍

2022-04-26 16:17 UTC, merged