Week1 [STEP 3] 임덤덤
yagom-academy/swift_starter-week1 pull request #121
Opened 2022-04-26 05:05 UTC by limdumb

코드를 작성 하였을때 기본적으로 이름 짓는것에 대해서 매우 고민을 많이 했습니다.
아무래도 .. 1..4번 미션이 내용물만 다르고 결과적으론 빼빼로를 만들어야 하는것이다 보니 각각 다 다르게 해야하나 생각을
좀 많이 했던것 같습니다.

아직도 .. 이름 짓는게 조금 햇갈려서 문서도 찾아보고 하는데 감이 잘 안잡히네요..
그래도 Step2에서 아리님이 피드백 잘 해주셔서 코드적으로는 작성하는데 우선적으로 큰 무리는 없었던것 같습니다 :)

감사합니다!

+순서도 수정본도 같이 진행하였습니다!
@leeari95

2022-04-26 06:04 UTC, leeari95 requested changes
임덤덤님 안녕하세요!
스텝3까지 구현하시느라 고생많으셨습니다! 👍🏻

아래 의견들은 어디까지나 제 의견이고, 정답은 아니니까 참고만 해주세요.

## 저의 의견

* 말씀하신 것 처럼 빼빼로를 만드는 기능을 구현해야하는 것인데, 함수가 다 따로 구현되어 있네요.
    * 그래서 코드가 중복되는 느낌이 들어요. 이러한 이유로 중복되는 부분은 리뷰를 따로 드리지 않았어요.
    * Todo대로 함수를 나누어 구현해보고, 해당 함수를 이용해서 실행 예시와 같은 빼빼로를 만들어보는 것은 어떨까요?
    * 그럼 코드도 훨씬 짧아지고 간결해질 것 같아요.
* STEP3의 순서도 작성이 빠져있는 것 같아요.
* github상에서는 파일이 보이는데, Xcode에서는 파일이 보이지 않아요.
    * 커밋할 때, 파일 경로가 누락이 되서 그런 것 같아요. 
<img width="339" alt="CodeStarterCamp_Week1" src="https://user-images.githubusercontent.com/75905803/165231957-5a2ae8a9-c79c-45e0-bac2-9bd186bc1ded.png"> <img width="285" alt="CodeStarterCamp_Week1" src="https://user-images.githubusercontent.com/75905803/165231981-054dd284-cdb1-4891-913b-a83de7cb0c58.png">
* 커밋 단위를 쪼개보면 어떨까요?
    * 현재 커밋들은 뭉태기 커밋이라 어떤게 추가, 수정, 삭제 된건지 파악이 어려워요.
    * 사실 지금같은 미니 프로젝트에서는 큰 문제가 되지는 않지만, 나중에는 꼭 분리하시는게 좋아요. 지금부터라도 연습해보면 어떨까요?
        * 커밋은 프로젝트가 어떻게 개발되고 있는지에 대한 역사[?]라고 생각하시면 어떨까요....?
    * 보통은 커밋 단위를 어떤 기능을 추가하거나, 삭제, 수정, 버그 수정, 혹은 네이밍 수정, 파일 삭제 등등... 이런 작은 단위로 나눠서 커밋을 해요.
* `Expressions are not allowed at the top level` 라는 오류는 왜나는걸까요?
    * DM으로도 주셨던 질문인데, main은 코드가 실행되는 파일이고, 새로 만든 파일의 경우는 정의부분이라고 생각해주시면 편합니다.
    * `아이스크림.swift`, `빼빼로.swift` 파일의 경우 함수를 정의해주시고,
    * `main.swift`에는 함수를 호출하는 코드를 작성하시면 됩니다.
* 네이밍 정말 어렵죠... 저도 아직도 어려운데요. 
    * 팁을 드리자면 Swift의 기본 함수들은 어떤식으로 네이밍이 되고있는지 참고해보면 도움이 되더라구요!
    * 그리고 함수가 어떤 기능을 하고있는지 생각해보고 네이밍을 하신다면 좀더 수월해지지 않을까 싶네요.

# 

이 외에 자세한 리뷰는 코멘트를 통해 남겨드렸어요.
혹시 리뷰에 대한 의문점이나, 어려운점이 있다면 편하게 DM주세여!
고생많으셨습니다. 😊

2022-04-26 06:04 UTC, leeari95 commented on CodeStarterCamp_Week1/main.swift
>  //
파일이 바뀐 흔적이네요.
이 주석은 어떤 의미로 남겨두신 건가요?

2022-04-26 06:04 UTC, leeari95 commented on CodeStarterCamp_Week1/main.swift
> +    }
함수로 따로 만들어주신 이유가 있으신가요?
제 개인적인 생각에는 따로 함수를 만들 필요 없이
print 함수를 바로 써도 될 것 같은데... 어떻게 생각하세요? 🤔

그리고.. 20번 라인 공백 컨벤션이 안맞는것 같네요.

2022-04-26 06:04 UTC, leeari95 commented on CodeStarterCamp_Week1/main.swift
> +        print("","\(firstStick)")
이렇게도 될 것 같은데요 ? 🤩

```suggestion
        print(" \(firstStick)")
```

2022-04-26 06:04 UTC, leeari95 commented on CodeStarterCamp_Week1/main.swift
> +func printFirstStick(length: Int) {
오.. 반복문의 횟수를 파라미터로 전달받고 있네요.
print 내부에 넣어줄 String도 파라미터로 전달받으면 어떨까요?
함수가 더 유연해질 것 같은데요?

함수 네이밍은 빼빼로 스틱이 더 명확할 것 같은데 어떠신가요?

2022-04-26 06:04 UTC, leeari95 commented on CodeStarterCamp_Week1/main.swift
> +}
이 함수도 바디와 토핑을 파라미터로 전달받으면 더 좋을 것 같아요.

2022-04-26 06:04 UTC, leeari95 commented on CodeStarterCamp_Week1/main.swift
> +        printFirstStick(length: firstStickHigh)
이 부분은 앞부분 공백이 다른데, 이유가 궁금합니다. 😁

2022-04-26 06:04 UTC, leeari95 commented on CodeStarterCamp_Week1/main.swift
> +func printMainBody(high: Int) {
빼빼로 바디가 더 명확하지 않을까요?

2022-04-26 06:04 UTC, leeari95 commented on CodeStarterCamp_Week1/main.swift
> +let firstToping: String = ""
입력할 값들을 따로 변수로 만들어 모아주셨네요.
이유가 궁금합니다! 🤔

2022-04-26 06:04 UTC, leeari95 commented on CodeStarterCamp_Week1/main.swift
> +            " ","\(body)","\(topping)",separator: "")
보통 이렇게 코드가 길어서 가독성을 위해 내려쓰는 경우에는
이런식으로 많이 쓰는 것 같더라구요!
```suggestion
    print(
        "\(topping)\(body)\n \(body)\(topping)",
        separator: ""
    )
```

콤마는 안써도 될 것 같아서 지워보았어요. 저는 오히려 콤마때문에 가독성이 안좋은 것 같은 느낌이 드네요. 🤔

2022-04-26 06:12 UTC, limdumb commented on CodeStarterCamp_Week1/main.swift
>  //
Expressions are not allowed at the top level
이 오류를 해결하면서 불필요한게 몇개 생성 되었었는데 그때 몇개는 지우고
남겨둔건 생성일자는 남겨두는게 좋겠다 싶어서 놔뒀던거 같습니다 :)

2022-04-26 06:18 UTC, limdumb commented on CodeStarterCamp_Week1/main.swift
> +    }
미션에서 몸통과 토핑을 매개변수로 받아 몸통을 그리는 함수를 그리라고 해서 만든 함수이다 보니 저 함수는 나중에 높이를 받아서 몸통을 만드는 함수 안에 들어갈 함수이다 보니 조금더 보기쉽게 하고싶어서 만든 함수였던거 같습니다. 혹시 아리님이 생각하시는 print함수를 바로 써도 될것같다는게 제가 잘 이해가 되지 않아서 어떤 방향성으로 가는게 조금더 좋을지 여쭤봐도 될까요??

+ 20번 라인 공백 컨벤션은 수정 하였습니다 :) 나중에 커밋 하겠습니다!

2022-04-26 06:19 UTC, limdumb commented on CodeStarterCamp_Week1/main.swift
> +        print("","\(firstStick)")
print 안에 \()코드가 들어가면 무조껀 , <- 따옴표를 써야하는줄 알고 있었습니다 !! 이렇게도 가능하단걸 지금 알았네요! 감사합니다

2022-04-26 06:21 UTC, leeari95 commented on CodeStarterCamp_Week1/main.swift
> +    }
가독성을 위해서 함수로 따로 만들어주신 것이군요!
제가 이야기했던 것은 
그냥 `print("\(toping)","\(body)")` 이 자체 한줄로도 가독성이 나쁘지 않다는 뜻으로 이야기한 내용이였어요.

2022-04-26 06:22 UTC, limdumb commented on CodeStarterCamp_Week1/main.swift
> +func printFirstStick(length: Int) {
길이(Int)에 따른 막대(빼빼로 손잡이)를 그리는 함수에 틀이 정해진줄 알고 일부러 길이(Int)만 매개변수로 받게끔 설정 해봤던거라 말씀 하신대로 print내부에 넣어줄것을 파라미터로 받는게 더 사용하기나 보기도 편할것 같습니다 :)

함수 네이밍은 말씀해주신게 더 명확한거 같아요! 수정 해보겠습니다 ^^!

2022-04-26 06:24 UTC, limdumb commented on CodeStarterCamp_Week1/main.swift
> +}
길이에 따라 몸통을 그리는 함수로 틀을 길이를 매개변수로 받고 몸통을 그리는 함수로 이해를 했다 보니까 printFirstBody를 따로 함수로 선언하고 그걸 반복하게 하는 함수를 그리다보니 high만 매개변수로 받았던것 같습니다 !

2022-04-26 06:25 UTC, limdumb commented on CodeStarterCamp_Week1/main.swift
> +        printFirstStick(length: firstStickHigh)
앞뒤 부분 가독성을 올리려고 위에오는 body 밑에 stick을 공백을 준것인데 혹시 이렇게 코드가 작성되면 어떤부분이 문제가 될수있는지 여쭤봐도 될까요?.?

2022-04-26 06:26 UTC, limdumb commented on CodeStarterCamp_Week1/main.swift
> +let firstToping: String = ""
미션 자체에 정해진게 길이에 따른 막대, 몸통과 토핑을 매개변수로 받는 함수 , 길이에따라 몸통을그리는 함수 등이 있다보니까 지정해두고 사용하면 편할꺼 같아서 let으로 상수선언을 하고 사용 했던것 같습니다 :)

2022-04-26 06:27 UTC, limdumb commented on CodeStarterCamp_Week1/main.swift
> +            " ","\(body)","\(topping)",separator: "")
ㅠㅠ 지금이라도 \()뒤에 콤마를 안써도 되는걸 알았습니다..너무감사합니다 주신 코드가 너무 깔끔하네요 전부다 수정을 해야겠어요!!!😊😊 감사해용~

2022-04-26 06:49 UTC, leeari95 commented on CodeStarterCamp_Week1/main.swift
> +        printFirstStick(length: firstStickHigh)
컨벤션이 안맞아서 오히려 가독성에 좋지 못한 것 같아요.
같은 라인인데, 들여쓰기가 되어있으니 코드를 처음보는 사람 입장에서는 착각할 수도 있을 것 같아요! 😊

2022-04-29 02:39 UTC, limdumb commented
최종 수정 완료 하였습니다 :)

2022-04-29 08:05 UTC, leeari95 approved these changes
수정사항 잘확인했습니다!
와우... 엄청 개선이 되었는데요?
정말 고생 많으셨어요. 순서도도 잘 수정해주신 것 같고,
파라미터를 적극 활용해주셔서, 이전보다 훨씬 가독성이 좋아졌네요 👍🏻
제 의견을 이렇게 적극적으로 반영해주셔서 너무 고맙습니다!!!

더이상 문제 없어서 머지해드릴게요. 다음 스텝에서 봐요 👋🏻😊

2022-04-29 08:05 UTC, leeari95 commented on CodeStarterCamp_Week1/PpePpeRo[Step3].swift
> +    print("                         ")
```suggestion
    print()
```

이렇게 해도 덤덤님이 원하는 결과가 나올 것 같아요 😊

2022-04-29 08:05 UTC, leeari95 commented on CodeStarterCamp_Week1/PpePpeRo[Step3].swift
> +}
함수로 예제를 깔끔하게 나누어주셨네요. 최고! 👍🏻
다만 First나 Seceond라는 이름보다는 
아몬드 빼빼로, 그냥 빼빼로, 누드 빼빼로 이런 이름으로 했으면 어땠을까 하는 생각도 드네요!

2022-04-29 08:06 UTC, merged