Week 1 [STEP 3] Jay Lee
yagom-academy/swift_starter-week1 pull request #123
Opened 2022-04-27 07:08 UTC by jay0614-lee

@oksunwoo  
STEP 3 PR 보내드립니다!

- 과제 조건대로 파일을 생성해서 진행하려고 하니 직접 함수 실행은 main.swift 에서만 가능하다는 것을 알게되어 프로그램 별로 파일을 나누고 함수를 작성한 후에 main.swift 에서 함수를 실행하였습니다.
- 토핑이 있는 경우와 없는 경우를 구분하기 위해서 .isEmpty 를 사용하였습니다. 
- 빼빼로 몸통을 출력하는 부분에서 빼빼로의 토핑 및 몸통 부분을 구분하기 쉽게 하기 위해서 " " 로 하나로 묶지 않고 쉼표(,)로 나누어 입력한 다음에 separator 항목을 사용하여 줄바꿈이 없이 출력되도록 작성하였습니다.

감사합니다!

2022-04-27 15:17 UTC, oksunwoo requested changes
<img width="126" alt="스크린샷 2022-04-28 오전 12 14 22" src="https://user-images.githubusercontent.com/55880539/165551840-c5b1b3c8-a215-4ee7-a7af-02a074204e6e.png">

출력예시입니다! 제이님이 짜신 코드와는 조금 다른것같지 않나요?ㅎㅎ
요구사항대로 부탁드립니다! 그리고 나만의 빼빼로도 없는 것 같네요!
요구사항 및 문서를 꼼꼼하게 읽는 것 또한 개발자의 역량 중 하나랍니다!
확인해보시고 수정 부탁드릴게요!
그리고 DM으로 기타 사항 남겨놓겠습니다 고생하셨어요!

2022-04-27 15:17 UTC, oksunwoo commented on CodeStarterCamp_Week1/drawPepero.swift
> +// 막대 그리는 함수 (길이 - Int)
코드에 주석은 남기지 않습니다!
주석이 작성되지 않을정도로 눈에 보기 좋은 코드를 작성하는 게 목적입니다!

2022-04-27 15:17 UTC, oksunwoo commented on CodeStarterCamp_Week1/drawPepero.swift
> +}
28번째 라인의 공백은 무엇때문에 생겼나요~ 컨벤션 통일 부탁드릴게요!

2022-04-27 15:17 UTC, oksunwoo commented on CodeStarterCamp_Week1/drawPepero.swift
> +}
swift 공식문서의 컨벤션에 따르면 
func a(b: Int)  와 같이 메서드 명 뒤 괄호는 붙어있는데 한번 그렇게 고쳐볼까요?

2022-04-27 16:27 UTC, jay0614-lee commented on CodeStarterCamp_Week1/drawPepero.swift
> +// 막대 그리는 함수 (길이 - Int)
처음에 작성할 때 잠깐 적어놓고 나중에 지운다는게 깜빡하고 그대로 두고 올렸었네요 삭제 진행했습니다!

2022-04-27 16:27 UTC, jay0614-lee commented on CodeStarterCamp_Week1/drawPepero.swift
> +}
공백 삭제하였습니다!

2022-04-27 16:27 UTC, jay0614-lee commented on CodeStarterCamp_Week1/drawPepero.swift
> +}
말씀하신 컨벤션대로 수정하였습니다!

2022-04-27 16:28 UTC, jay0614-lee commented
@oksunwoo 
코멘트 달아주신 내용들 수정하고 빼빼로 함수에 정보도 출력되도록 변경하였습니다
나만의 빼빼로 함수 실행문도 추가하였습니다

확인 부탁드립니다!

2022-04-28 06:16 UTC, oksunwoo requested changes
해당 부분 수정해주시면 바로 머지해드릴게요~

2022-04-28 06:16 UTC, oksunwoo commented on CodeStarterCamp_Week1/drawPepero.swift
> +
요구사항 출력의 띄어쓰기와는 살짝 달라보이는데요! 
막대길이 다음 한칸, 빼빼로 출력 다음도 한칸 비도록 출력해볼까요~

2022-04-28 10:06 UTC, jay0614-lee commented on CodeStarterCamp_Week1/drawPepero.swift
> +
말씀하신 내용 추가하였습니다!

2022-04-28 11:08 UTC, merged