Week 1 [STEP 3] Oh Sung Ah
yagom-academy/swift_starter-week1 pull request #124
Opened 2022-04-27 11:53 UTC by delight010

이번주 피드백 시간에 객체지향을 배우게 되어,
클래스의 인스턴스를 매개변수로 받는 함수를 작성하였습니다.

원래는 구조체로 하다가, 구조체로 만들게되면 내부의 인스턴스들을 수정할 수가 없었습니다.
let, var 설정에 관계없이 let으로 설정되는 것 같습니다.

2022-04-27 16:41 UTC, jaemuYeo requested changes
성아님 안녕하세요!!
코드를 통해 코멘트 남겨놓았습니다!
객체를 생성하면서 Pepero라는 클래스를 생성 후 
클래스 내부에 함수를 구현하지 않고 밖에서 작성하신 이유가 있으신가요?
내부에 구현했다면 구조체로 하셨어도 정상적으로 되었을거예요~
그렇게 된다면  함수의 매개변수 없이 구현할 수 있었을 것 같아요🙂

구조체로 Pepero타입을 정의했을 때에 
```swift
// 토핑, 몸통 그리는 함수
func settingToppingOnPeperoBody(_ pepero: Pepero) {
    if pepero.topping.count > 0 {
        pepero.body = "\(pepero.topping + pepero.body)\n \(pepero.body + pepero.topping)"
    }else{
        pepero.body = " \(pepero.body)"
    }
}
```
이 함수에서 에러가 발생하게 되는데
```swift
func settingToppingOnPeperoBody(_ pepero: Pepero) {
    var pepero = pepero
    
    if pepero.topping.count > 0 {
        pepero.body = "\(pepero.topping + pepero.body)\n \(pepero.body + pepero.topping)"
    }else{
        pepero.body = " \(pepero.body)"
    }
}
```
이렇게 구현했을때 에러는 사라지지만 어떻게 프린트 되는지 확인해 보고,
그 이유에 대해 알아볼 수 있을까요??

2022-04-27 16:41 UTC, jaemuYeo commented on CodeStarterCamp_Week1/main.swift
> +class Pepero {
클래스와 구조체를 다루는 프로젝트는 3주차 프로젝트에 진행되어있으니
추후에 다시 사용하되 지금은 좋은 방향으로 구현하셨으니 참고해서 코멘트 남기겠습니다!
멋져요 👍

2022-04-27 16:41 UTC, jaemuYeo commented on CodeStarterCamp_Week1/main.swift
> +func peperoInfo(_ pepero: Pepero) {
빼빼로의 정보를 출력하는 함수를 따로 분리하셨군요! 좋습니다 👏

2022-04-27 16:41 UTC, jaemuYeo commented on CodeStarterCamp_Week1/main.swift
> +    }else{
else 앞뒤로 띄어쓰기가 필요할 것 같아요!
아래함수도 수정해주세요!

2022-04-27 16:41 UTC, jaemuYeo commented on CodeStarterCamp_Week1/main.swift
> +    if pepero.topping.count > 0 {
조건문의 0 도 매직넘버가 될 수 있다 생각하는데 성하님의 생각은 어떠신가요?

2022-04-27 16:41 UTC, jaemuYeo commented on CodeStarterCamp_Week1/main.swift
> +        for _ in 0..<(pepero.bodyHeight / 2) {
(pepero.bodyHeight / 2) 수식의 의미를 네이밍해서 변수로 생성 후 넣어주어도 좋을 거 같아요 😀

2022-04-27 16:41 UTC, jaemuYeo commented on CodeStarterCamp_Week1/main.swift
> +func makePepero(_ pepero: Pepero) {
기능분리 후 makePepero함수를 통해 최종적으로 호출하는 방법이 너무 좋습니다 👏

2022-04-28 07:08 UTC, delight010 commented
@jaemuYeo 
**<클래스 내부에 함수를 구현하지 않고 밖에서 작성한 이유>**
step3에서 매개변수를 받으라고 적혀있어서, 클래스 외부에 함수를 작성하게되었습니다! 
이런경우는 클래스 내부에 작성해서 메소드를 가져와서 실행하는 게 더 깔끔하겠네요!

**<조건문의 0은 매직넘버가 될 수 있는 가?>**
매직넘버라고 생각합니다. 소스코드 내부에 있는 구체적인 숫자값이기 때문입니다.
숫자값의 의미를 알기 어려운 경우에는 이름이 있는 변수나 상수로 만들어서 사용하는 것이 좋다고 생각합니다.
하지만 이 부분은 변수나 상수로 할당하지않아도 의미를 알 수 있는 숫자값이기 때문에 그대로 숫자를 쓰게 되었습니다.

<구조체로 구현하게 된다면>
```
func settingToppingOnPeperoBody(_ pepero: Pepero) {
    var pepero = pepero
    
    if pepero.topping.count > 0 {
        pepero.body = "\(pepero.topping + pepero.body)\n \(pepero.body + pepero.topping)"
    }else{
        pepero.body = " \(pepero.body)"
    }
}
```

1. 나오는 오류: Cannot assign to property: 'pepero' is a 'let' constant

> pepero의 프로퍼티는 상수이기 때문에 재할당할 수 없습니다.

2. makePepero()를 사용하여 빼빼로를 출력할 경우, body의 문자열이 변경되지 않음. 이유는?

> 클래스는 참조타입이기 때문에 할당되어있는 프로퍼티에 직접 접근하여 값을 변경할 수 있습니다.
> 하지만 구조체로 만들어진 pepero의 프로퍼티는 상수이기 때문에 값을 재할당할 수 없습니다.

> var pepero = pepero로 변수를 선언하게되면, 매개변수로 받은 pepero를 복사하여 할당하게 되는 지역변수가 됩니다.
> 복사된 pepero(변수) 값은 변경할 수 있으나, 이는 settingToppingOnPeperoBody 함수 내에서만 사용되는 지역변수 이기 때문에, 구조체의 프로퍼티(매개변수)에 직접 접근하는 것이 아닙니다.
> 그렇기 때문에 구조체의 프로퍼티는 변경되지않고 구조체를 생성할 때 들어가는 초기값 그대로 남아있게됩니다.


설명하는 것도 많이 어렵네요. 클래스와 구조체 비슷하면서도 다른 타입이라 글로만 봐서는 확실히 이해하기가 어려운 것 같아요.
이번에 연습하면서 예전보다 좀 더 확실히 알게 된 것 같습니다.

2022-04-28 15:17 UTC, jaemuYeo reviewed
성아님 Week1 고생많으셨습니다!!
구조체와 클래스에 대해 조금 가까워졌나요??
전보다 확실히 코드가 깔끔해진 것 같아요 👍
이번 프로젝트는 여기서 머지 진행하겠습니다! 
몇 가지 코멘트 남겨놓은 것들은 수정 후 week2로 넘어가주세요~~
week2 까지는 객체를 다루지 않아서 다음 프로젝트는
클래스와 구조체 없이 한 번 구현해보아요☺️

2022-04-28 15:17 UTC, jaemuYeo commented on CodeStarterCamp_Week1/main.swift
> +var starPepero = Pepero(bodyHeight: 10, body: "***", topping: "", stickHeight: 4)
이 곳에서는 변수 대신 상수로 하는게 어떨까 생각해봅니다!😀

2022-04-28 15:17 UTC, jaemuYeo commented on CodeStarterCamp_Week1/main.swift
> +    let stickBody: String = " | |"
프로퍼티와 init() 사이에 개행을 통해 구분지어주세요!

2022-04-28 15:17 UTC, merged