Week1 [Step3] taru02
yagom-academy/swift_starter-week1 pull request #130
Opened 2022-05-04 07:34 UTC by mobaetaru02

😆 반가워요 호댕! @yanghojoon  
step3를 해보았지만 잘하고 있는지 어떤지 모르겠어 조금은 심란한 하루입니다!ㅋㅋ
이번 pr도 잘부탁드릴게요~
+ 저번에 알려주신 commit 메시지 템플릿은 다음부터 사용해보도록 하겠습니다!
## 고민한점

> if?

조건문을 사용한다면 더 좋은 코드를 짤 수 있을꺼라고 생각했지만, 현재는 조건문을 배우지 않을상태이고 Step3에서 요구하는 점은 
Week1에서 배운 내용을 토대로 코드를 짜는거라고 생각했다.
그래서 조건문 없이 코드를 짜보려했지만 능력부족으로 인해 빼빼로 몸통의 길이가 홀수일 경우 정상적으로 출력할 수 없는 코드가 되었다

이는 어떻게 하는지 힌트를 받고 싶다

> naming?

코드이름 짓기가 너무 어려운것 같다.
naming의 중요성을 보았지만, 좋은 naming이 어떤것인지는 아직 잘 모르겠다.
알고 있는 규칙을 토대로 이번 코드의 함수등의 이름을 지어보았으나, 개인적으로 느끼기에 너무 길어서 좋지 않은것 같은 느낌을 받았다

이 또한 어떤 이름이 좋은 이름인지 예시를 보고 싶다.

>컨벤션?

step2를 마치고 다른 분들의 PR을 조금 보았는데 생소한 단어들이 있었다.
그중 눈에 띄었던 것은 컨벤션인데 컨벤션 통일이라는 단어를 꽤 보았는데 검색해보아도 어떤뜻인지 정확히 알 수가 없었다

어떤 뜻일까?

2022-05-04 08:52 UTC, yanghojoon requested changes
안녕하세요, 타루 @mobaetaru02 
충분히 잘해주고 계십니다 🥳🥳

## 질문주신 내용에 대한 답변 
### 1️⃣ If 조건문에 대한 사용 
일단 Week1에서 조건문을 배우시지 않았으나, 사용을 하실 수 있다면 조건문을 사용해도 될 것 같습니다. 
다만 몸통 길이가 홀수인 경우 제대로 출력이 되지 않는다는게 잘 이해가 가지 않습니다. 
어떤 경우를 말씀하시는 걸까요?

### 2️⃣ 네이밍 관련 고민
네이밍에 대해 일단 고민을 하시는 것 자체가 좋은 것 같아요. 
저는 개인적으로 길다고 좋지 않은 네이밍은 아니라고 생각합니다. 
오히려 너무 축약해서 알아보기 힘든 네이밍이 더 안좋은 네이밍이라 생각합니다. 
작성해주신 네이밍의 경우 대체로 괜찮다고 생각되긴 합니다. 

만약 조금 더 잘 읽히는 네이밍으로 작성하시려면 Argument Label을 사용해보시는 것도 좋을 것 같네요
Ex) `printStick(length: Int)` -> `printStick(by length: Int)`
다만 파라미터가 많아질 경우에는 오히려 안써주는 경우가 더 가독성이 좋은 경우도 있기는 합니다. 

세부적인 네이밍은 아래 코멘트로 말씀드릴게요.

### 3️⃣ 컨벤션
컨벤션은 코드 작성 스타일이라고 이해해주셔도 좋을 것 같습니다. 
언제 줄바꿈을 하고, 들여쓰기는 몇 칸 할 것인지 등에 대해 통일하는 것을 코드 컨벤션을 맞춘다고 이해해주시면 될 것 같아요.

## 고민해보시면 좋을 부분
### 1️⃣ 순서도
현재 문자열 보간법 형태로 출력 메세지를 그대로 작성해주셨는데 이를 실제 사용하는 문장형태로 변경하는 것은 어떨까요? 
순서도의 역할이 코드를 짜기 전 논리 흐름을 정리하는 것인 만큼 문법과 관련없이 작성되는 것이 맞을 것 같아요.

### 2️⃣ 파일 분리
파일 분리를 해주실 때 기존 아이스크림 관련 코드는 주석처리를 해주신 것 같습니다. 
파일 분리를 통해 처리할 수 있지 않았을까요? 

그리고 불필요한 파일들이 생성된 경우가 있는 것 같습니다.

2022-05-04 08:52 UTC, yanghojoon commented on CodeStarterCamp_Week1/main.swift
> +*/
사용하지 않는 주석은 전부 제거해주시면 좋을 것 같아요

2022-05-04 08:52 UTC, yanghojoon commented on CodeStarterCamp_Week1/File.swift
> +import Foundation
해당 파일은 따로 필요가 없을 것 같은데 따로 두신 이유가 있으신가요?

2022-05-04 08:52 UTC, yanghojoon commented on CodeStarterCamp_Week1/main.swift
> +makePepero(peperoShape: "***", peperoHeight: 10, peperoTopping: " ", stickLength: 4)
파라미터를 통해 재사용이 가능한 함수로 구현하신 점 좋습니다 👍

2022-05-04 08:52 UTC, yanghojoon commented on CodeStarterCamp_Week1/pepero.swift
> +func printInfo(shape: String, height: Int, topping: String, lenght: Int) {
오타가 있는 것 같아요

2022-05-04 08:52 UTC, yanghojoon commented on CodeStarterCamp_Week1/pepero.swift
> +func printStick(length: Int) {
위에서도 예로 말씀드렸지만 argument label의 사용도 고려해보시면 좋을 것 같아요

2022-05-04 08:52 UTC, yanghojoon commented on CodeStarterCamp_Week1/pepero.swift
> +let bar: String = "|"
이부분은 꼭 전역 변수로 두어야 하나요?

2022-05-04 08:52 UTC, yanghojoon commented on CodeStarterCamp_Week1/pepero.swift
> +    print("<정보>")
함수에서 print를 여러번 호출하고 있으시군요. print를 한 번만 사용하고 출력할 수 있지는 않을까요??

2022-05-04 08:52 UTC, yanghojoon commented on CodeStarterCamp_Week1/pepero.swift
> +func makePepero(peperoShape: String, peperoHeight: Int, peperoTopping: String, stickLength: Int) {
하나의 함수로 묶어 호출할 수 있도록 한 점 좋습니다 😄

2022-05-04 08:52 UTC, yanghojoon commented on CodeStarterCamp_Week1/stickCookie.swift
> +import Foundation
이 파일도 불필요한 파일같아요

2022-05-04 08:52 UTC, yanghojoon commented on CodeStarterCamp_Week1/pepero.swift
> +        print(" \(bodyShape)\(toppings)")
만약 toppings가 하나만 들어가지 않고 2개 이상 들어간다면 (ex: &&) 띄워쓰기 한칸으로 처리가 어려울 것 같아요. 
혹시 이 부분을 처리할 수 있는 방법 없을까요?

2022-05-04 08:52 UTC, yanghojoon commented on CodeStarterCamp_Week1/pepero.swift
> +    printInfo(shape: peperoShape,
해당 함수에선 파라미터 별로 줄바꿈을 해주셨고 밑에 있는 printBody에선 파라미터 별로 줄바꿈을 해주시지 않았는데 혹시 타로만의 기준이 있으신가요?

2022-05-04 09:07 UTC, mobaetaru02 commented on CodeStarterCamp_Week1/pepero.swift
> +func printInfo(shape: String, height: Int, topping: String, lenght: Int) {
아이 저거 뭐야ㅋㅋㅋㅋ

2022-05-06 07:32 UTC, mobaetaru02 commented
1. 파일 분리를 해주실 때 기존 아이스크림 관련 코드는 주석처리를 해주신 것 같습니다.
파일 분리를 통해 처리할 수 있지 않았을까요?

+  파일분리를 통해 왜 무분별한 전역변수 사용이 좋지 못한지 안 것 같습니다
전역변수를 무분별하게 사용하면 파일간에 충돌이 잦아질 수 있어서 인 것 같은데 맞을까요?

+ 쓸모없는 파일들을 다 지우고 커밋을 했는데도 커밋에서는 쓸모없는 파일들이 사라지지 않네요 어떡하죠??


2. 만약 조금 더 잘 읽히는 네이밍으로 작성하시려면 Argument Label을 사용해보시는 것도 좋을 것 같네요

+ swift API Design Guidelines를 참고해봤지만 정확히 어떤기능을 하는지 잘 모르겠어요. 다른 참고할만한 자료가 있을까요?

 3. print 한번으로 모든 info를 출력할 수 없는가?


+ ("""

""") 를 사용하여 해결했습니다!

4. 만약 toppings가 하나만 들어가지 않고 2개 이상 들어간다면 (ex: &&) 띄워쓰기 한칸으로 처리가 어려울 것 같아요.
혹시 이 부분을 처리할 수 있는 방법 없을까요?

+ 잘 모르겠어요! 도움! 힌트를 부탁해요!!

5. 일단 Week1에서 조건문을 배우시지 않았으나, 사용을 하실 수 있다면 조건문을 사용해도 될 것 같습니다.
다만 몸통 길이가 홀수인 경우 제대로 출력이 되지 않는다는게 잘 이해가 가지 않습니다.
어떤 경우를 말씀하시는 걸까요?

+ peperoHeight에 홀수를 넣으면 그 값 만큼 출력되는것이 아니라 홀수-1의 값만큼 출력되는걸 말한겁니다! (ex peperoHeight에 5를 넣어주면 실제로 출력되는 빼빼로 그림은 4줄이 나옵니다)

2022-05-06 14:07 UTC, yanghojoon commented
모아서 답변해주시기 보단 코멘트에 바로 답글 달아주시면 좀 더 답변이 용이할 것 같아요 🙏

### 1️⃣ 파일이 사라지지 않고 남아있는 이유
이는 Delete로 파일을 제거할 때 Move to Trash로 하지 않아 발생한 문제 같네요. 
[링크](https://github.com/yagom-academy/swift-starter-week2/pull/200#discussion_r856411344)에 자세히 정리되어 있으니 한 번 살펴보세요~

### 2️⃣ Argument Label
혹시 어떤 식으로 검색을 하시나요? 보통 Swift~ / iOS~ 를 붙이고 검색하고자 하는 키워드를 찾아보시면 거의 나올 것 같습니다. 
- https://docs.swift.org/swift-book/LanguageGuide/Functions.html#ID166

### 3️⃣ 토핑이 2개 이상인 경우 처리 방식 
String의 경우 count를 통해 글자 수를 셀 수 있습니다. 이를 활용해 띄워쓰기를 할 수 있을 것 같아요

### 4️⃣ 홀수의 처리 
조건문 사용이 가능하시다면 조건문으로 처리해보셔도 좋을 것 같습니다. 만약 조건문을 처리하지 않더라도 반올림이나 이런 것들을 사용해 해결할수도 있을 것 같네요.

2022-05-08 08:08 UTC, merged