week1 [STEP 1] suhjun
yagom-academy/swift_starter-week1 pull request #34
Opened 2022-04-13 12:01 UTC by suhjun

week1 STEP 1 입니다!

2022-04-13 22:03 UTC, Kioding commented
suhjun님! 
첫 PR 환영합니다🙌 
담당 학습도우미를 배정해드릴게요. 
다음 PR부터는 학습도우미를 직접 태그해주시면 됩니다 ☺️                        
                       
@yanghojoon          
담당 학습도우미는 호댕입니다 :)

2022-04-14 05:57 UTC, yanghojoon requested changes
안녕하세요, suhjun! @suhjun 
첫 PR이신데 PR 제목도 잘 작성해주시고 올바른 branch에 잘 보내주셨군요! 👏 

다만 Step이 나눠져 있는 만큼 하나의 스텝이 마무리되면 PR보내주시면 감사하겠습니다.

2022-04-14 05:57 UTC, yanghojoon commented on README.md
> +- (답) 컴퓨터는 수 많은 트랜지스터로 이루어져있고 트랜지스터는 전기 신호에 따라 두가지 의 상태를 구분하여 처리합니다. 이를 바탕으로 컴퓨터도 이진법을 사용하고 있습니다. 이진법을 사용해서 얻을 수 있는 장점으로는 오류의 최소화와 효율성이 있습니다.
왜 이진법을 사용하면 오류가 최소화되고 효율적이라고 생각하셨나요?

2022-04-14 05:57 UTC, yanghojoon commented on README.md
> +- 또 메모리를 저장하는 용도인 기억장치를 보조기억장치라고 부릅니다.
보조기억 장치가 메모리를 저장하는 용도일까요?

2022-04-14 05:57 UTC, yanghojoon commented on README.md
> +- (답) 주기억 장치는 CPU가 처리 하고 있는 메모리를 저장하는 기억장치입니다. 그래서 그때그때 필요한 메모리를 가지고 와서 읽고 저장하기 떄문에 주기억장치라고 부른다고 생각합니다.
1. 주기억장치가 CPU가 처리하고 있는 "메모리"를 저장하는 것이 맞을까요? 
2. 또한 왜 휘발성 메모리인 RAM을 주기억 장치로 쓰고있는 것일까요? 전원을 꺼도 데이터가 살아있는 보조기억 장치가 왜 주기억 장치의 역할을 하지 않는 걸까요?

2022-04-14 05:57 UTC, yanghojoon commented on CodeStarterCamp_Week1/main.swift
> +func drawIcecream() -> Void {
네이밍을 카멜케이스를 사용하여 잘 적어주셨네요! 👍👍

2022-04-14 05:57 UTC, yanghojoon commented on CodeStarterCamp_Week1/main.swift
> +func drawIcecream() -> Void {
혹시 반환타입으로 Void를 명시해주신 이유가 있으실까요?

2022-04-14 05:57 UTC, yanghojoon commented on CodeStarterCamp_Week1/main.swift
> +        print("***********")
for문을 통해 반복문을 잘 이용해주셨군요! 다만 이렇게 작성을 해주실 경우 다른 높이나 너비를 가지는 아이스크림을 만드려면 매번 다른 메서드를 만들어야 할 것 같습니다. 

재사용이 가능한 메서드를 어떻게 작성할 수 있을까요?

2022-04-14 05:57 UTC, yanghojoon commented on CodeStarterCamp_Week1/main.swift
> +        print("    | |    ")
이 부분도 재사용 가능한 메서드로 변경하면 조금 더 유연한 코드를 만들 수 있을 것 같습니다.

2022-04-14 06:07 UTC, suhjun commented on README.md
> +- (답) 컴퓨터는 수 많은 트랜지스터로 이루어져있고 트랜지스터는 전기 신호에 따라 두가지 의 상태를 구분하여 처리합니다. 이를 바탕으로 컴퓨터도 이진법을 사용하고 있습니다. 이진법을 사용해서 얻을 수 있는 장점으로는 오류의 최소화와 효율성이 있습니다.
이진법은 0과 1로 이루어져 있어서 다른 진법들보다 틀릴 확률이 낮다고 생각했습니다. 그리고 오류가 날 확률이 낮아지면 효율적이 된다고 생각했어요.

2022-04-14 06:10 UTC, suhjun commented on README.md
> +- 또 메모리를 저장하는 용도인 기억장치를 보조기억장치라고 부릅니다.
아! 메모리가 아니라 데이터라고 하는게 맞을까요?

2022-04-14 06:14 UTC, suhjun commented on README.md
> +- (답) 주기억 장치는 CPU가 처리 하고 있는 메모리를 저장하는 기억장치입니다. 그래서 그때그때 필요한 메모리를 가지고 와서 읽고 저장하기 떄문에 주기억장치라고 부른다고 생각합니다.
1. 메모리가 아니라 데이터라고 하는게 맞는것 같아요.
2. 주기억장치 RAM은 CPU가 필요로 하는 데이터를 저장하고 있는데 필요해지지 않는 데이터는 지우고 다른 데이터를 또 저장하고 있어야 해서 휘발성 메모리를 사용하는 것 같습니다. 그리고 보조기억장치는 데이터를 가져오는데 오래걸리기 때문에 주기억 장치의 역할을 하지 않습니다.

2022-04-14 06:15 UTC, yanghojoon commented on README.md
> +- 또 메모리를 저장하는 용도인 기억장치를 보조기억장치라고 부릅니다.
넵! 주기억장치를 보통 '메모리'라고 부르고, CPU에서 제어 / 연산할 데이터를 저장하고 있다고 알고 있습니다. 

보조기억장치 또한 메모리 자체를 저장하기 보단 데이터를 저장하는 것으로 알고 있구요.

2022-04-14 06:16 UTC, suhjun commented on CodeStarterCamp_Week1/main.swift
> +func drawIcecream() -> Void {
반환값이 따로 없으면 Void를  써야한다고 생각했어요, 이제 보니까 따로 적을 필요가 없을 것 같아요

2022-04-14 06:18 UTC, suhjun commented on CodeStarterCamp_Week1/main.swift
> +        print("***********")
높이랑 너비를 함수의 인자값으로 받는 함수를 작성해야 할거 같아요

2022-04-14 07:29 UTC, yanghojoon commented on README.md
> +- (답) 주기억 장치는 CPU가 처리 하고 있는 메모리를 저장하는 기억장치입니다. 그래서 그때그때 필요한 메모리를 가지고 와서 읽고 저장하기 떄문에 주기억장치라고 부른다고 생각합니다.
2. 말씀해주신 대로 보조기억장치는 주기억장치에 비해 읽고 쓰는 속도가 훨씬 느리기 때문에 주기억장치를 주기억장치로 쓰는 것이 아닌가 생각합니다. 
다만 휘발성 메모리여서 주기억장치이지 않을까 하는 부분에 대해선 전원이 종료되거나 해당 어플리케이션이 종료되어 메모리에 내려갈 경우 저장하고 있던 데이터가 휘발되는데 이 시점이 데이터를 지우고 싶은 순간과 항상 일치되진 않는다고 생각됩니다. 
따라서 저는 속도 측면에서 주기억장치를 주기억장치로 선택한 것이 아닌가 생각되네요~! 🧐

2022-04-14 07:30 UTC, yanghojoon commented on CodeStarterCamp_Week1/main.swift
> +func drawIcecream() -> Void {
물론 반환 타입을 명시해주는 것이 잘못되었다는 것은 전혀 아닙니다! 
다만 대부분 반환타입이 Void만 있을 경우 생략하는 경우가 잦은데 혹시 따로 명시해준 이유가 있으신가 해서 여쭤봤습니다.

2022-04-14 07:38 UTC, yanghojoon requested changes

2022-04-14 07:38 UTC, yanghojoon commented on CodeStarterCamp_Week1/main.swift
> +            print("||")
분기 처리를 통해 짝수일 때도 막대가 중앙에 올 수 있도록 처리를 해주셨군요! 👍

2022-04-14 07:38 UTC, yanghojoon commented on CodeStarterCamp_Week1/main.swift
> +        let newWidth = width/2 - 1
막대 옆에 빈 공간을 위한 width인 만큼 네이밍을 수정해볼 수 있을 것 같습니다.

2022-04-14 07:38 UTC, yanghojoon commented on CodeStarterCamp_Week1/main.swift
> +            print("*", terminator: "")
terminator를 사용하여 줄바꿈이 되지 않고 다음 print를 할 수 있게 처리해주신 점 좋습니다!

2022-04-14 08:38 UTC, suhjun commented on CodeStarterCamp_Week1/main.swift
> +        let newWidth = width/2 - 1
막대 옆에 빈공간을 그대로 써서 barLeftSpace로 새로 네이밍 해봤습니다.

2022-04-14 09:39 UTC, yanghojoon approved these changes

2022-04-14 09:40 UTC, merged