Week1 [STEP 1] Lily
yagom-academy/swift_starter-week1 pull request #43
Opened 2022-04-14 04:18 UTC by hililyy

2022-04-14 07:02 UTC, leeari95 requested changes
릴리님 안녕하세요 ~
스텝2 구현하시느라 고생 많으셨습니다 🎉
파라미터를 잘 활용해보셨네요. 멋져요 👍🏻

그런데 몇가지 궁금한 점이 있어서 한번 의견드려봅니다.
질문 주신 부분에 대해서는 따로 코멘트를 남겨드렸으니 참고부탁드립니다!

#

> ### 순서도를 살펴보았는데, 코드 흐름과 맞지 않는 부분이 있는 것 같습니다.
* i부터 7보다 작은지 검사해야할 것 같지 않나요?
* 그리고 i가 7보다 작지 않을때, false일 때의 화살표가 누락되어 있는 것 같아요.
* i에 1을 더하고 bar 출력이 맞는걸까요...?

drawIceCream과 drawBar가 함께 그려져 있는데, 나누어서 그리면 좀더 파악이 쉬울 것 같은데
어떻게 생각하세요? 😁

#

> ### 주석을 제거하신 이유가 궁금하네요.

정말 궁금해서 여쭤보는 겁니다!

#

> ### 중간에 코드 컨벤션이 맞지 않는 것을 발견했어요.
* 공백이 있는 부분이 있고, 없는 부분이 있어요

이 부분은 큰~ 문제는 아니지만.. 그래도 일관성 있게 컨벤션을 맞춰주는게 좋지 않을까요?

#

한번 고민해보시고 수정 후 재리뷰 부탁드립니다!
고생 많으셨습니다! 😊

2022-04-14 07:10 UTC, leeari95 commented
> 재 리뷰 요청은...
<img width="1243" alt="image" src="https://user-images.githubusercontent.com/75905803/163332895-0a69e648-ff9c-4ba6-86e1-ad0bbc1cb90f.png">

이 부분을 클릭해주시면 됩니다! 😁

2022-04-17 08:09 UTC, hililyy commented on CodeStarterCamp_Week1/main.swift
> +        for j in 0...10 {
읽어보았습니다 감사합니다!

2022-04-17 08:09 UTC, hililyy commented on CodeStarterCamp_Week1/main.swift
> +func drawBar (bar :String){
좀 더 명확하게 수정하겠습니다!

2022-04-17 08:10 UTC, hililyy commented on CodeStarterCamp_Week1/main.swift
> -//
예전에 다른 분께 간단하게 배웠을 때 프로젝트 생성 후 저 부분의 주석을 지우시길래 항상 무의식적으로 지웠던 것 같습니다..🤣 혹시 이 부분을 지우지 않는것이 좋을까요??

2022-04-17 08:10 UTC, hililyy commented on CodeStarterCamp_Week1/main.swift
> +    for i in 0...3{
공백 모두 동일한 패턴으로 수정하였습니다!

2022-04-18 02:31 UTC, leeari95 commented on CodeStarterCamp_Week1/main.swift
> -//
아뇨. 주석을 지우신 이유가 궁금해서 여쭤보았습니다.
만약 지우지 않는다면, 그에 대한 합당한 이유가 있으면 주석을 남겨두어도 문제없는 부분입니다.
참고해주세요 😁

2022-04-18 02:34 UTC, leeari95 commented on CodeStarterCamp_Week1/main.swift
> +func drawIceCream(iceCream :String){
공식문서 예제코드들을 확인해보면 보통은 파라미터가 끝나고 중괄호가 시작하기 전에 공백을 넣어주는 것을 확인할 수 있습니다.
[Swift Language Guide - Functions](https://docs.swift.org/swift-book/LanguageGuide/Functions.html)

2022-04-18 02:37 UTC, leeari95 commented
수정사항 잘 확인했습니다. 😄
다만 아직까지 사용하지 않는 i, j 값들이 아직도 살아있어서 경고가 뜨는 것을 확인했는데요.
이 부분은 어떤 이유로 남겨두신 것인지 궁금합니다.
와일드 카드 패턴에 대해서 읽어보셨다면 이 값들을 어떻게 처리하면 좋을까요?

그리고 추가적인 코멘트도 [한개](https://github.com/yagom-academy/swift_starter-week1/pull/43#discussion_r851845149) 남겨드렸는데, 확인 부탁드리겠습니다. 😁

2022-04-18 05:25 UTC, hililyy commented on CodeStarterCamp_Week1/main.swift
> +func drawIceCream(iceCream :String){
참고하겠습니다 감사합니다!

2022-04-18 05:42 UTC, hililyy commented
> 수정사항 잘 확인했습니다. 😄 다만 아직까지 사용하지 않는 i, j 값들이 아직도 살아있어서 경고가 뜨는 것을 확인했는데요. 이 부분은 어떤 이유로 남겨두신 것인지 궁금합니다. 와일드 카드 패턴에 대해서 읽어보셨다면 이 값들을 어떻게 처리하면 좋을까요?
> 
> 그리고 추가적인 코멘트도 [한개](https://github.com/yagom-academy/swift_starter-week1/pull/43#discussion_r851845149) 남겨드렸는데, 확인 부탁드리겠습니다. 😁

사용하지 않은 i와 j값을 남겨둔 이유는 순서도를 그릴때 변수 i와 j를 사용했기 때문에 남겨두었습니다🤣 수정하였습니다!

2022-04-18 14:54 UTC, merged