Week1 [STEP2] jeongmin(정민)
yagom-academy/swift_starter-week1 pull request #53
Opened 2022-04-14 12:30 UTC by jeongmin-l

@jaemuYeo 

잼킹! 안녕하세요
두 번째 스텝 PR요청 드립니다!

처음 제가 짰던 코드는 네이밍이 width, height 등 구체적이지 못했는데 이름 짓는 것에 고민을 좀 해서 구체적이게 지어봤습니다!

또 이번에 PR요청을 하면서 문제가 좀 생겼었는데
커밋, 푸시 후 pr요청을 하기 직전 수정할 부분을 발견해서 수정을 했습니다

그래서 이전에 있던 커밋을 취소하고 다시 커밋하려고 제 포크 레포지토리에 갔더니 
푸시가 반영은 되어 있었지만 git clone을 통해 제 코드를 받아보면 
마지막 merge 기준의 파일들로 되어있어서 당황했습니다

해결 해보려고 이것저것 해보다 옆에 fetch upstream에 fetch and merge를 눌렀더니 커밋이 하나 더 생긴것 같아요..

이럴 경우 어떻게 reset을 하고 다시 작업할 수 있나요?

2022-04-14 15:28 UTC, jaemuYeo requested changes
정민님 Step2도 멋지게 해주셨군요!!
for문에 대해 잘 이해하신 것 같아요!!
그리고 네이밍에 관해서도 신경을 많이 쓰신 것 같습니다 👍👍
이번 스텝도 그렇고 앞으로 진행될 저의 코멘트에 대해서
모두가 맞다고 생각하시지 마시고, 정민님의 의견도 꼭 표출해주세요!!
그리고 틀려서 달린 코멘트 이외에도 정말 의도가 궁금해서 달리는 것도 있을 거니
너무 깊게 생각하지 않으셨으면 좋겠습니다 😀

---

### 코드
코드에 대한 리뷰는 따로 달려있으니 참고해주세요!!
아직 머지는 하지 않고, 조금만 더 수정해보도록 할까요??
커밋에 대한 부분도 앞으로 `커밋컨벤션`을 조금씩 연습해보는 것도 좋을 것 같아요
[이 사이트](https://doublesprogramming.tistory.com/256) 또는
구글에 `커밋 메시지 남기는법`, `커밋 컨벤션` 등등 검색해보며 앞으로 커밋할 때 
해보시길 바래요!!
보통 기능단위별로 커밋을 진행하는 편인데
예를들어 이번 스텝에서는 하나의 함수당 한번의 커밋, 순서도 추가에서 한번의 커밋
이렇게 세 번정도의 커밋이 나올 수 있었겠죠??

---

### 순서도
코드 변경 후에 한번 더 수정이 이루어졌으면 좋겠어요!!
두 개의 함수를 따로 순서도로 그려본 다음에 연관지어서 하나의 순서도로 표현해보는 것도
좋은 연습 방법일거예요~
최대한 많이 쪼개보는 습관을 가지면 좋은 것 같더라구요 😂
그리고 이렇게 png 파일을 추가하는 방법도 있지만
README에 멋지게 이미지를 넣는 방법도 있답니다!!

---

### 질문이 대한 답변

이 부분은 저도 한번 더 고민해보겠습니다!
push가 되었을 때와 안되었을때의 차이가 있을 것으로 생각되는데
따로 디엠드릴테니 디스코드에서 같이 해보아요~~

2022-04-15 04:02 UTC, jeongmin-l commented on CodeStarterCamp_Week1/main.swift
> +    for iceCreamHeight in 1...8 {
_를 사용하려니 순서도를 제 코드와 비교했을 때 보는 사람 입장에서는 뭘 뜻하는지 모르는 코드일것 같아 루프상수를 사용 했는데
상수를 따로 지정해주는 방법을 생각하지 못했네요 😅

2022-04-15 04:02 UTC, jeongmin-l commented on CodeStarterCamp_Week1/main.swift
> +        print()
네! 맞아요! widthOfIceCream만큼 반복 출력하고 나니 terminator 옵션 지정 때문에 줄바꿈이 이뤄지지 않더라구요
\n 개행을 위해서 넣었습니다 😊

2022-04-15 04:46 UTC, jeongmin-l commented on CodeStarterCamp_Week1/main.swift
> +func drawIceCreamStick() {
통일성 있게 수정 했습니다! 😆

2022-04-15 08:03 UTC, jaemuYeo reviewed
코드와 순서도가 멋지게 수정되었네요!! 👍
고생하셨습니다!!
한 가지 말씀드리고 싶은 것은 커밋 메시지에 refactor, docs 만 적혀있는데
`refactor: 어떠한 함수를 어떻게 변경함, 내부에 변수를 추가함`
와 같이 적어주시면 좋답니다!! 다음 스텝에서 진행해 보아요!!
커밋은 나의 코드가 변화되는 과정을 기록하는 것이니 매우 중요하답니다😉
그럼 스텝2는 머지 진행할게요!! 다음 스텝에서 만나요~

2022-04-15 08:03 UTC, merged