week 1 [STEP1] sonshinwoo
yagom-academy/swift_starter-week1 pull request #6
Opened 2022-04-12 07:40 UTC by Sonshinwoo

test 중입니다...

2022-04-12 08:20 UTC, Kioding commented
첫 PR 환영합니다🙌 
담당 학습도우미를 배정해드립니다. 
다음 PR부터는 학습도우미를 직접 태그해주시면 됩니다 ☺️                        
                     
@yeahg-dev          
담당 학습도우미 릴리입니다!

지금은 이미 PR을 보내신 상황이니 
미션 요구사항을 끝내면 담당 학습도우미를 한번 더 코멘트로 태그부탁드려요!

2022-04-15 14:12 UTC, Sonshinwoo commented
@yeahg-dev 
안녕하세요 두번째 PR 내용입니다. 
깃허브를 처음 사용해봐서 사용하는게 너무 복잡하고 이렇게 하는게 맞는지 잘모르겠네요 ㅎㅎ
아 그리고 깃허브에 관련하여 질문 하나만 드려도 될까요?

Q. 깃허브에서 commit을 한후 push를 진행하면 제 branch에 내용이 변경되어야 하는데 제 branch를 보면 변경이 아직 안됐는데 이게 master분이 merge를 하지 않아서 코드쪽에서  안보이는 건가요?

2022-04-16 11:59 UTC, yeahg-dev commented
안녕하세요 신우님!

두가지 질문에 대한 커밋을 잘 나누어 진행하신 후, 푸시까지 잘 진행해주셨네요👍
수고많으셨습니다!
저두 처음 깃 사용했을 때 멘붕에 빠졌던 기억이 나네요,, 
언제든 깃 사용하다 막히는 부분 있으면 편하게 메시지 주시면 같이 봐드릴게요!

다만, 현재 스텝1이 머지가 되지 않은 상태에서 스텝2를 진행해주셨어요.
이 부분은 조금의 오해가 있었던 것 같은데요, 
현재 올려주신 PR은 스텝1에 관한 것이므로
이 PR이 야곰아카데미의 브랜치로 머지가 완료된 후에, step2에 대한 PR은 또 다른 새로운 Pull Request를 만들어서 진행해주셔야 해요.

따라서 현재 PR을 머지한 후에, 스텝2에 대한 리뷰는 스텝2 PR에서 진행하도록 하겠습니다!

DM에서 말씀드린것과 같이, 현재 머지전에 수정되어야할 사항이 2가지가 있어요!
1. PR의 제목 양식
   현재 제목이 test인데요, `야곰아카데미 캠핑사이트 > Course > 📢 Pull Request 보낼 때 꼭 확인하세요!`에서 양식 확인 후, 맞춰서 수정해주시면 됩니다.
2. base 브랜치를 신우님 브랜치로 수정
   현재 야곰아카데미의 메인 브랜치로 타겟이 설정되어 있습니다. 브랜치를 아래 사진과 같이 신우님 브랜치로 수정부탁드립니다!
<img width="1106" alt="스크린샷 2022-04-16 오후 8 46 25" src="https://user-images.githubusercontent.com/81469717/163673717-c3ff1dc8-a8ea-4c83-8a5b-1c6b71aec4bf.png">

위 두가지만 수정되면 바로 머지 진행하겠습니다
하시다 궁금한 점 있으면 언제든 디엠주세요😊


### 질문에 대한 답변
> Q. 깃허브에서 commit을 한후 push를 진행하면 제 branch에 내용이 변경되어야 하는데 제 branch를 보면 변경이 아직 안됐는데 이게 master분이 merge를 하지 않아서 코드쪽에서 안보이는 건가요?
로컬에서 `commit` 을 하고, 해당 커밋을 리모트로`push`를 하면 리모트의 브랜치에서도 해당 커밋이 반영이됩니다.
신우님 레포지토리에서 브랜치를 변경하지 않아 안보이는 것으로 생각이드는데요🤔

아래 그림과 같이 신우님 브랜치로 설정되어있는지 한번 확인해보시겠어요??
<img width="796" alt="스크린샷 2022-04-16 오후 8 23 55" src="https://user-images.githubusercontent.com/81469717/163673188-a82dc177-8295-48e9-b4f0-be51f742db48.png">

2022-04-16 12:15 UTC, yeahg-dev requested changes
안녕하세요 신우님!

두가지 질문에 대한 커밋을 잘 나누어 진행하신 후, 푸시까지 잘 진행해주셨네요👍
수고많으셨습니다!
저두 처음 깃 사용했을 때 멘붕에 빠졌던 기억이 나네요,, 
언제든 깃 사용하다 막히는 부분 있으면 편하게 메시지 주시면 같이 봐드릴게요!

다만, 현재 스텝1이 머지가 되지 않은 상태에서 스텝2를 진행해주셨어요.
이 부분은 조금의 오해가 있었던 것 같은데요, 
현재 올려주신 PR은 스텝1에 관한 것이므로
이 PR이 야곰아카데미의 브랜치로 머지가 완료된 후에, step2에 대한 PR은 또 다른 새로운 Pull Request를 만들어서 진행해주셔야 해요.

따라서 현재 PR을 머지한 후에, 스텝2에 대한 리뷰는 스텝2 PR에서 진행하도록 하겠습니다!

DM에서 말씀드린것과 같이, 현재 머지전에 수정되어야할 사항이 2가지가 있어요!
1. PR의 제목 양식
   현재 제목이 test인데요, `야곰아카데미 캠핑사이트 > Course > 📢 Pull Request 보낼 때 꼭 확인하세요!`에서 양식 확인 후, 맞춰서 수정해주시면 됩니다.
2. base 브랜치를 신우님 브랜치로 수정
   현재 야곰아카데미의 메인 브랜치로 타겟이 설정되어 있습니다. 브랜치를 아래 사진과 같이 신우님 브랜치로 수정부탁드립니다!
<img width="1106" alt="스크린샷 2022-04-16 오후 8 46 25" src="https://user-images.githubusercontent.com/81469717/163673717-c3ff1dc8-a8ea-4c83-8a5b-1c6b71aec4bf.png">

위 두가지만 수정되면 바로 머지 진행하겠습니다
수정이 완료되시면 재요청버튼을 눌러주세요. 
<img width="1310" alt="test by Sonshinwoo · Pull Request #6 · yagom-academy:swift_starter-week1 2022-04-16 21-16-46" src="https://user-images.githubusercontent.com/81469717/163674674-a1c3683c-204d-4b19-818b-b69188e75aa5.png">

하시다 궁금한 점 있으면 언제든 디엠주세요😊


### 질문에 대한 답변
> Q. 깃허브에서 commit을 한후 push를 진행하면 제 branch에 내용이 변경되어야 하는데 제 branch를 보면 변경이 아직 안됐는데 이게 master분이 merge를 하지 않아서 코드쪽에서 안보이는 건가요?
로컬에서 `commit` 을 하고, 해당 커밋을 리모트로`push`를 하면 리모트의 브랜치에서도 해당 커밋이 반영이됩니다.
신우님 레포지토리에서 브랜치를 변경하지 않아 안보이는 것으로 생각이드는데요🤔

아래 그림과 같이 신우님 브랜치로 설정되어있는지 한번 확인해보시겠어요??
<img width="796" alt="스크린샷 2022-04-16 오후 8 23 55" src="https://user-images.githubusercontent.com/81469717/163673188-a82dc177-8295-48e9-b4f0-be51f742db48.png">

2022-04-16 12:15 UTC, yeahg-dev commented on README.md
> + test 작업중입니다...
불필요한 띄어쓰기와 글은 삭제해주는 것이 어떨까요?

2022-04-16 15:16 UTC, lovleyponyo commented
test중입니다

2022-04-18 13:33 UTC, yeahg-dev commented
제목 양식과 브랜치 수정 모두 확인했습니다.
머지할게요!

다음 스텝에서 만나요🚀

2022-04-18 13:33 UTC, merged