Week1 [STEP 2] 애쉬
yagom-academy/swift_starter-week1 pull request #65
Opened 2022-04-15 07:46 UTC by ash-you

@yanghojoon 

Week1 [STEP 2] 진행하여 PR 보내드립니다!
한가지 진행하면서 해결하지 못한 것이 있는데 처음에 git commit 시 commit 메시지를 레지스토리 이름으로 잘못 기재해서 메시지를 수정하고 싶었는데 잘 진행이 되지 않은 것 같습니다. :(
구글에 검색해보니 원격저장소에 push 전에 git commit --amend 를 사용하라고 해서 사용해봤는데  어디다가 수정 메시지를 입력하는 것인지... 알 수 없었습니다.
때문에 결국 두가지 커밋 모두 push 되었습니다ㅠㅠ

2022-04-15 08:28 UTC, yanghojoon requested changes
이번 스텝도 고생많으셨습니다. 애쉬님! @ash-you

반복문을 잘 사용하셔서 아이스크림이 제대로 출력되도록 구현을 잘 해주셨군요! 👍

## 🤔 고민해보시면 좋을 부분 
### 1. 함수의 재사용성 증가 
현재 makeIceCream, makeIceCreamBar 함수의 경우 정해진 아이스크림만 그릴 수 있을 것 같습니다. 조금 더 다양한 아이스크림을 그릴 수 있는 메서드를 구현할 수 없을까요?

### 2. 순서도
출력되는 부분을 순서도로 표현할 때 적합한 도형을 사용하셨는지 궁금합니다!

2022-04-15 08:28 UTC, yanghojoon commented on CodeStarterCamp_Week1/main.swift
> +func makeIceCream () {
이 함수를 사용하면 항상 ***********가 8개가 쌓인 아이스크림 형태만 생성할 수 있을 것 같아요! 
조금 더 다양한 아이스크림을 구현하는데 재사용할 수 있는 함수로 구현할 수 없을까요?

2022-04-15 08:28 UTC, yanghojoon commented on CodeStarterCamp_Week1/main.swift
> +func makeIceCreamBar () {
아이스크림 바 또한 마찬가지로 조금 더 다양한 형태를 구현할 수 있도록 재사용 가능한 함수를 만들 수 있을 것 같아요

2022-04-15 08:28 UTC, yanghojoon commented on CodeStarterCamp_Week1/main.swift
> +makeIceCream()
하나의 함수만 호출하여 아이스크림을 만들 수는 없을까요?
아이스크림을 구현하는 함수가 늘어난다면 매번 실행할 때마다 모든 함수를 작성하다보면 함수 호출을 누락할 수 있을 것 같습니다.

2022-04-15 08:28 UTC, yanghojoon commented on CodeStarterCamp_Week1/main.swift
> +    for layer in 1...8 {
단순히 `i`같은 의미없는 변수명을 사용하지 않고 `layer`로 사용하신 점 좋습니다 👏
다만 현재 layer 변수를 따로 사용하는 곳이 없는 것 같습니다. 이런 경우에 어떻게 처리를 할 수 있을까요?

2022-04-15 08:28 UTC, yanghojoon commented on CodeStarterCamp_Week1/main.swift
> +func makeIceCream () {
함수 명 뒤에 ()를 띄우신 이유가 있으실까요?

2022-04-15 08:28 UTC, yanghojoon commented on CodeStarterCamp_Week1/main.swift
> +func makeIceCreamBar () {
여기도 마찬가지로 함수 명 다음에 괄호를 띄우신 이유가 궁금합니다!

2022-04-15 08:28 UTC, yanghojoon commented on CodeStarterCamp_Week1/main.swift
> +func makeIceCream () {
카멜 케이스를 사용해 함수명을 잘 작성해주셨군요!

2022-04-15 09:52 UTC, ash-you commented on CodeStarterCamp_Week1/main.swift
> +makeIceCream()
위에 코멘트 주신 3가지 사항을 고려해서 아이스크림과 아이스크림 바 모두 layer의 매개변수를 받아서 재사용 가능한 형태로 수정해보았습니다! 매개변수는 몸통/막대기 모두 한번에 받아서 하나의 함수만 호출해도 아이스크림이 생성될 수 있도록 수정 해보았습니다!

2022-04-15 09:55 UTC, ash-you commented on CodeStarterCamp_Week1/main.swift
> +    for layer in 1...8 {
이 부분은 xcode에서도 알럿을 띄워주어서 확인해보았는데, "_" 형태로 수정하거나 지우라는 제안을 주더라구요! 그래도 layer 처럼 의미가 있는 변수명이 좋지 않을까 하였지만... 알럿을 없애기 위해 "_" 형태로 수정해보았습니다! (지웠을 때는 for in의 형태가 아니라 오류가 발생하여 진행하지 않았습니다 🥲

2022-04-15 09:56 UTC, ash-you commented on CodeStarterCamp_Week1/main.swift
> +func makeIceCreamBar () {
이 부분은 무의식적으로 띄어쓰기를 쓰다보니 습관이 불러낸 실수인 것 같습니다 :(

2022-04-15 09:57 UTC, ash-you commented on CodeStarterCamp_Week1/main.swift
> +    for layer in 1...8 {
언더바를 쓴 것인데 댓글을 작성하니 마크다운이 되어 보이지 않네요 아이고 언더바 형태로 수정하였습니다!

2022-04-15 10:07 UTC, yanghojoon commented on CodeStarterCamp_Week1/main.swift
> +    for layer in 1...8 {
혹시 `_`로 변경을 하셨던데 `_`가 무엇인지 아실까요?
그리고 지운다는 말씀이 
```swift 
for in 1...8 { }
``` 
이런 형태로 for in 사이에 아무것도 적지 않는 것을 말씀하신 걸까요?

2022-04-15 10:15 UTC, yanghojoon requested changes

2022-04-15 10:15 UTC, yanghojoon commented on CodeStarterCamp_Week1/main.swift
> +func makeIceCream(iceCreamLayer: Int, iceCreamBarLayer: Int) {
하나의 함수에 아이스크림을 만드는 반복문을 합치셨군요! 

메서드를 하나의 기능만을 하도록 분리하고 싶다면 

```swift 
func makeIceCream() {
    makeIceCreamBody()
    makeIceCreamBar()
}

func makeIceCreamBody() { }
func makeIceCreamBar() { }
```
이런 형태로 사용해볼 수도 있을 것 같아요! 물론 지금 변경하신 부분이 맞지 않다는 것은 아닙니다!

2022-04-15 10:15 UTC, yanghojoon commented on CodeStarterCamp_Week1/main.swift
> +func makeIceCream(iceCreamLayer: Int, iceCreamBarLayer: Int) {
매개변수를 활용하여 조금 더 유연한 코드를 작성하셨군요 👍
현재 아이스크림과 막대의 높이를 정할 수는 있지만 아이스크림의 너비는 따로 정할 수 없는 것 같아요🙀

그리고 너비가 홀수일 경우 막대가 한쪽으로 치우치는 문제가 있을 것 같네요?! 혹시 이런 상황에도 대처할 수 있도록 하려면 어떻게 하는 것이 좋을까요?

2022-04-15 10:15 UTC, yanghojoon commented on CodeStarterCamp_Week1/main.swift
> +
현재 import를 하고 2줄, 함수와 함수 호출부 사이에 2줄을 띄우셨군요?
혹시 애쉬님만의 코딩 컨벤션이 있으실까요?

2022-04-15 10:18 UTC, yanghojoon commented
출력의 경우 보통 순서도에서 평행사변형을 쓰는 것 같아요! 출력하는 부분의 도형이 제대로 쓰였는지 확인해보셔도 좋을 것 같습니다.

2022-04-18 07:01 UTC, ash-you commented on CodeStarterCamp_Week1/main.swift
> +    for layer in 1...8 {
언더바는 와일드카드 패턴이라고 보았습니다! for문 범위 내에서 변수명을 사용하지 않는 경우에 언더바로 생략이 가능한 것으로 확인하였네요! 지운다는 것은 저런 형식이 맞는데, 저런 형식으로는 되지 않는다고 하여서 swift에서의 'removing it' 을 직관적으로 받아들인 것인가 하는 의문이 듭니다🤔

2022-04-18 07:07 UTC, ash-you commented on CodeStarterCamp_Week1/main.swift
> +func makeIceCream(iceCreamLayer: Int, iceCreamBarLayer: Int) {
호댕님이 제안해주신 형태를 이용해서 다시 재구성 해보았습니다! 아이스크림의 너비는 생각해보지 못한 부분이어서 아이스크림을 만들 때, 너비와 높이 모두 매개변수로 받는 형태로 수정하였습니다!

아이스크림바를 만들 때, 너비가 홀수인 경우를 따로 출력하려면 if문을 써야할 것 같아 너비가 짝수일 때와 홀수일 때를 따로 작성하였습니다 :)
짝수일 때는 4byte를 차지하는 형태의 바를 출력하여 정중앙에 들어올 수 있도록 하였고, 홀수일 때는 3byte를 차지하는 형태의 바를 출력하여 이 역시 중앙에 들어올 수 있게 수정해보았네요
대신 순서도가 복잡해지는 것 같아 makeIceCreamBody와 makeIceCreamBar를 따로 작성하여 커밋하였습니다 😅

2022-04-18 07:10 UTC, ash-you commented on CodeStarterCamp_Week1/main.swift
> +
사실 코딩 컨벤션이라는 단어 조차 처음 들어보아서... 검색해보니 참고자료가 많이 나오는 것 같습니다 ㅠㅎㅎ 자주 보면서 익혀봐야겠습니다~!

2022-04-18 10:02 UTC, yanghojoon requested changes

2022-04-18 10:02 UTC, yanghojoon commented on CodeStarterCamp_Week1/main.swift
> +                print(" ", separator: "", terminator: "")
separator를 지정해주신 이유가 있으실까요?

2022-04-18 10:02 UTC, yanghojoon commented on CodeStarterCamp_Week1/main.swift
> +                print(" ", separator: "", terminator: "")
여기도 마찬가지로 separator를 작성해주신 이유가 궁금합니다.

2022-04-18 13:10 UTC, ash-you commented on CodeStarterCamp_Week1/main.swift
> +func makeIceCreamBar(iceCreamWidth: Int, barLayer: Int) {
네네! Height로 변수명을 수정하는 것이 통일감 있을 것 같아서 수정해보았습니다 ㅎ

2022-04-18 13:12 UTC, ash-you commented on CodeStarterCamp_Week1/main.swift
> +                print(" ", separator: "", terminator: "")
기본값으로 공백이 추가적으로 발생하면 예상한 것과 다른 모양이 출력될 수 있을 것 같아서 아예 공백없이 출력될 수 있도록 직관적으로 수정해보았습니다! 막대가 쏠려서 출력될 수 있을 것 같아서 두군데 모두 기본값의 공백을 지워서 작성하였습니다

2022-04-18 13:14 UTC, ash-you commented on CodeStarterCamp_Week1/main.swift
> +    else if iceCreamWidth % 2 == 1 {
전달주신 링크 확인하였습니다! 무언가 문법을 쓸 때는 공식문서를 자주 확인해 봐야겠습니다 ㅠ_ㅠ

2022-04-18 13:52 UTC, merged