Week1 [STEP 3] Onestar
yagom-academy/swift_starter-week1 pull request #67
Opened 2022-04-15 09:57 UTC by oneStar92

@oksunwoo
토니!! STEP 3 PR입니다.
커밋 컨벤션도 활용해 보았고 브랜치 따로 만들어서 작업 후 머지도 해봤습니다...
코멘트가 적었으면 ㅠㅠㅠㅠ

궁금한점은 저번에 알려주신 underscore를 함수에 사용했습니다. 이런 형식은 처음인데 너무 막 사용하는게 아닌가 싶습니다.
어떻게 하다보니 의미가 계속 겹치는거 같아서 함수의 인자 거의 모든 부분에 underscore를 사용하게 됐네요. 잘못 사용한건가요?

2022-04-17 09:33 UTC, oksunwoo requested changes
전반적으로 코드를 잘 작성해주셨네요👏
기능별로도 함수 잘 분리해주신점이나, 커밋메시지도 단위별로 잘 나뉘어있네요!
많은 노력을 하신것처럼 보입니다.

코드도 잘 짜시는 것 같으니 한번 그럼 가독성에 대해 고민을 해볼까요?
현재 코드에서는 printPeperoOnOrder 메서드가 가장 메인이 되는 역할을 하는것 같은데,
메서드의 순서를 변경하는 것만으로도 가독성을 개선할 수 있으니, 다른사람이 읽을때 어떻게 읽혀야 잘읽힐지 고민해보시고 메서드 순서 변경까지 해보시는 거 추천드릴게요!

2022-04-17 09:33 UTC, oksunwoo commented on pepero.swift
> +func addToppingToBody(_ body: String, _ topping: String, _ lengthCount: Int) {
본문에 있는 모든 메서드명이 print인데, 토핑추가 하는 부분만 print가 아니네요
이 메서드는 토핑이 있으면 출력을 하는 역할을 하고 있는데 혹시 얘만 메서드명을 add로 하신 이유가 무엇인가요?

2022-04-17 15:46 UTC, oneStar92 commented on pepero.swift
> +    for lengthCount in 1...stickLength {
순서도 작성 시 반복문 표현을 단편으로 "~ 보다 큰가"라는 조건으로만 표현하다보니 그랬습니다.
순서도 작성 방법을 다시 찾아보고 다른 방법이 있는 것을 알게되었습니다.
하지만 현재는 해당 함수를 수정하는 과정에서 while문으로 변경하였습니다.

2022-04-17 15:47 UTC, oneStar92 commented on pepero.swift
> +func printPStick(_ stickLength: Int) {
해당 함수는 현재 makePeperoStick으로 네이밍을 다시하였습니다.

2022-04-17 15:51 UTC, oneStar92 commented on pepero.swift
> +func printPStick(_ stickLength: Int) {
함수명의 Naming을 바꾸면서 이에 맞게 파라미터의 External Name을 howLong으로 설정하였습니다

2022-04-17 15:53 UTC, oneStar92 commented on pepero.swift
> +func addToppingToBody(_ body: String, _ topping: String, _ lengthCount: Int) {
코드를 작성당시엔 코드도 가독성이 필요한지 몰랐습니다.
가독성을 고민해서 해당 함수는 makePeperoBodyMold로 네이밍 하였습니다.

2022-04-17 15:54 UTC, oneStar92 commented on pepero.swift
> +func printPeperoInfo(_ bodyLength: Int, _ body: String, _ topping: String, _ stickLength: Int) {
수정하였습니다.

2022-04-17 15:55 UTC, oneStar92 commented on pepero.swift
> +        addToppingToBody(body, topping, lengthCount)
해당 함수의 네이밍을 바꾸고 External Name을 사용하여서 다르게 디자인 해봤습니다.

2022-04-17 16:25 UTC, oneStar92 commented
### 수정사항

* makePeperoStick(howLong stickLength: Int) -> String
 가독성을 생각해서 빼빼로의 스틱을 만드는 함수라는 네이밍을 하였고 파라미터에 external name을 howLong으로 네이밍 하여서 빼빼로 스틱을 얼마나 길게 만들 것이냐? 라고 물어보는 식의 네이밍을 하였습니다.
위의 방식하고 makePeperoStick(length: Int) -> String 형태의 네이밍도 고민했습니다.
makePeperoStick(length: Int) -> String 이러한 형식으로 하게 되면 makePeperoStick(length: stickLength) 이런 식으로 함수를 호출하게 되는데 제 생각에는 이상하지 않은 거 같아서 질문드립니다.

*  makePeperoBodyMold(_ topping: String, on body: String, toppingPosition: Int) -> String
 makePeperoBodyMold 함수 또한 가독성을 생각하여서 네이밍 한 결과입니다. 함수 이름을 처음에 addToppingToBody로 한 이유는 토핑과 몸통 출력 함수를 구현하는데 말 그대로 몸통의 양쪽 중 한 곳에 토핑을 더하는 거라고만 생각하여서 add라는 네이밍을 하였습니다.
계속해서 고민한 결과 초콜릿, 사탕을 만들 때 사용하는 틀을 mold라고 하는 게 생각나서 결국 해당 함수는 mold를 만드는 것과 같다는 생각이 들어 makePeperoBodyMold라고 네이밍 하였습니다.
파라미터들 또한 함수를 호출하게 되면 makePeperoBodyMold(topping, on: body, toppingPosition: count%2)이런 형식으로 호출하게 되는데 이를 읽어보면 `toppingPosition에 맞게 body위에 토핑을 올린 빼빼로 몸통 틀을 만들어라.`라고 읽는다고 생각해서 이렇게 네이밍 하게 되었습니다. 제가 생각하는 가독성이 이런 형태가 맞는지 궁금하네요...

* makePeperoBody(_ topping: String, on body: String, howLong bodyLength: Int) -> String
 makePeperoBody 함수는 위 두 개의 함수의 네이밍을 하면서 얻은 결과를 합쳐서 해놓은 함수라고 생각하시면 될 거 같습니다.

* printPeperoOnOrder(body: String, topping: String, bodyLength: Int, stickLength: Int)
 코멘트 주신대로 printPeperoOnOrder 함수의 파라미터 순서를 조금 바꿔놨습니다.

* 전반적으로 코드를 수정하였습니다.
저는 코드에도 가독성이 필요한지 몰랐네요...
항상 요구 사항에 맞게 동작만 하는 코딩테스트식의 코딩만 해와서 그런지 코드에도 가독성이 필요한지 몰랐습니다...
그래서 전반적으로 네이밍을 다시 하고 해당 네이밍에 맞게 동작하는 방향으로 코드를 수정해 봤습니다.
처음 가독성을 생각하고 코드를 작성해봤는데 많이 이상한 느낌이네요...

2022-04-18 08:39 UTC, oksunwoo requested changes
정말 너무 보기좋은 코드였습니다! 코드에서 굉장한 노력이 엿보이네요! 가독성도 매우 좋아졌습니다
API 가이드라인 중 Good 파트에 있는 예시가 아래와 같은데 현재 원스타의 코드가 많이 닮았네요!
<img width="455" alt="스크린샷 2022-04-18 오후 5 32 26" src="https://user-images.githubusercontent.com/55880539/163781109-05a0c11c-0ac9-4a8f-b937-bb15773ea4c6.png">

howlong 부분만 해결하면 될 것 같습니다!

추가적으로 메서드의 위치변경에 대해 말씀드렸었는데 제 설명이 조금 부족했나봅니다! 
<img width="1270" alt="스크린샷 2022-04-18 오후 5 33 50" src="https://user-images.githubusercontent.com/55880539/163781303-1784eb1d-db72-43cb-9f4d-069ce4712bc9.png">

코드를 보시면 printPeperoOnOrder 메서드 내부의 순서는 information, body, stick 순서로 되어있는데, 실제 코드도 printPeperoOnOrder를 맨위로 올리고 해당 순서에 맞게 변경하시면 코드의 가독성이 매우 향상될 것으로 보입니다!

그리고 메서드 역할분리는 정말정말 잘하셨습니다!👏

2022-04-18 08:39 UTC, oksunwoo commented on pepero.swift
> +func printPeperoInfomation(_ body: String, _ topping: String, _ bodyLength: Int, _ stickLength: Int) {
Infomation -> Information으로 바꿔볼까요?

2022-04-18 08:39 UTC, oksunwoo commented on pepero.swift
> +func makePeperoStick(howLong stickLength: Int) {
이 부분은 원스타가 고민하신 두번째 방법인, makePeperoStick(length: Int) -> String  가 더 좋아보입니다!

2022-04-18 08:39 UTC, oksunwoo commented on pepero.swift
> +    return peperoBodyMold
여기 작성하신부분을 포함하여 print 부분을 따로 구현하신 것 정말 칭찬드립니다!
각 메서드의 역할이 잘 분리된 느낌이이에요! 메서드 명 역시 구현을 따라가고있네요
쉽지않으셨을텐데 많은 노력의 흔적이 보입니다

2022-04-18 09:02 UTC, merged