Week1 [Step 2] OneE
yagom-academy/swift_starter-week1 pull request #72
Opened 2022-04-15 15:03 UTC by One-E12

@jaemuYeo

문제점을 찾았어요...compare에 main으로 놓고 PR을 올렸네요 ㅠㅠ 죄송해요 잼킹 ㅠㅠ 

드디어 코멘트를 남기네요 잼킹... ㅜㅜ
사실 이 PR보내기 전에 레포지토리를 두번이나 삭제했답니다....... 😥

레포지토리에 제가 바로바로 커밋 하는 것들이 올라왔으면 좋겠어서 삭제했다가, 갑자기 이미 있는~ 이러면서 오류가 떠서 그냥 바탕화면?에 있던 것들도 모조리 삭제하고 다시 포크해왔어요...하하...

그래도 오후에 잼킹이 많이 알려주신 덕분에 오늘 배운 내용들은 확실히 기억할 것 같습니다 :) 감사해요 정말!!!

사실 수정_수정_진짜최종수정_완 이런 느낌의 PR이라 질문할거리가 많이 없어진 것 같아요😆
제 순서도 올려둘게요! 
![Icecream](https://user-images.githubusercontent.com/97447840/163586901-a83308d5-0b31-4dad-ab0f-7be4aa6f63fc.png)

2022-04-15 15:56 UTC, jaemuYeo commented
고생 많으셨어요 원이!! 👍
아직 Xcode도 그렇고 문법도 그렇고 많이 낯설었을텐데
이번 스텝을 통해 조금 친해지셨나요??
너무 잘 따라와주고 계셔요!! 멋집니다 ㅎㅎ 😀
몇몇 수정해야할 사항들이 있어서 코멘트를 통해 전달드릴게요~

---

## 코드
함수의 네이밍도 잘 지어주셨고, 두 개의 함수 모두 잘 작동되게 구현하셨네요!!
다만 애플이 제안하는 Swift Design Guidelines에서 띄어쓰기는 어떻게하고 있는지
숙지해주시고 코드 수정해주셨으면 좋겠습니다!!
잘 모르겠다면 캠프사이트의 학습자료를 참고하셔도 좋아요!

`고칠 부분 = 중괄호`
`고칠 부분 print("\(xdan)x\(i)=\(xdan*i)")`


금방 캐치하실 거예요 걱정마세요!

---

## 커밋메시지
디스코드에서 나눴던 대화 중 커밋 컨벤션에 대해 기억하시나요??
다음 스텝에서는 참고하셔서 커밋해주시면 좋을거같아요!!
이번에 수정하시면서 아이스크림 만드는 함수와 구구단 구현 함수의 파일을 나눠보고
어떻게 커밋하면 좋을지 고민하고 PR 제출해주세요!!
해결이 안되시면 언제든 질문 주세요 😊

---

## 레포지터리 삭제에 대하여

종종 여러 작업들을 실수하는 경우가 발생한답니다!! 너무나 당연한 일이예요,, ㅠㅠ
그럴때마다 했던 작업들을 모조리 날려버리고 새로 작성한다면 너무 끔찍하겠죠?
지금은 몇 줄 안되는 코드겠지만 수 백, 수 천 줄로 작성된 코드를 다 날리고 처음부터 하게되면,, 상상이 가시나요 ㅎㅎ
무언가 실수 했을 때 깃을 통해 어떻게 원하는 시점으로 돌아갈 수 있는지에 대해
좀더 알아보시면 좋을거 같아요!! 꽤나 어려울거예요!! 저도 어렵습니다 😫

---

## 순서도
순서도의 배경이 검은색이여서 그런가 글씨가 잘 보이지 않아요 ㅠㅠ
제가 다크모드로 사용해서 그럴수도 있어요 !
그리고 순서도에 대한 의문점도 있는데요!!
Body를 만드는 것과 Bar를 만드는 구조는 비슷하니 하나의 함수로 예로들어 말씀드릴게요!
`makeIcecreamBody()` 함수가 호출되면 어떠한 과정도 거치지 않고 바로 *를 출력할까요??
무언가 조건식이 먼저 나오고 내부 실행문이 실행될거라 생각해요!! 원이의 생각은 어떠신가요?

---

코멘트에 대해 생각해보시고, 조금의 수정 후 다시 PR 보내주시면 검토 후 머지 진행하겠습니다!

2022-04-15 15:58 UTC, jaemuYeo reviewed
고생 많으셨어요 원이!! 👍
아직 Xcode도 그렇고 문법도 그렇고 많이 낯설었을텐데
이번 스텝을 통해 조금 친해지셨나요??
너무 잘 따라와주고 계셔요!! 멋집니다 ㅎㅎ 😀
몇몇 수정해야할 사항들이 있어서 코멘트를 통해 전달드릴게요~

---

### 코드
함수의 네이밍도 잘 지어주셨고, 두 개의 함수 모두 잘 작동되게 구현하셨네요!!
다만 애플이 제안하는 Swift Design Guidelines에서 띄어쓰기는 어떻게하고 있는지
숙지해주시고 코드 수정해주셨으면 좋겠습니다!!
잘 모르겠다면 캠프사이트의 학습자료를 참고하셔도 좋아요!

`고칠 부분 = 중괄호`
`고칠 부분 print("\(xdan)x\(i)=\(xdan*i)")`

금방 캐치하실 거예요 걱정마세요!

---

### 커밋메시지
디스코드에서 나눴던 대화 중 커밋 컨벤션에 대해 기억하시나요??
다음 스텝에서는 참고하셔서 커밋해주시면 좋을거같아요!!
이번에 수정하시면서 아이스크림 만드는 함수와 구구단 구현 함수의 파일을 나눠보고
어떻게 커밋하면 좋을지 고민하고 PR 제출해주세요!!
해결이 안되시면 언제든 질문 주세요 😊

---

### 레포지터리 삭제에 대하여
종종 여러 작업들을 실수하는 경우가 발생한답니다!! 너무나 당연한 일이예요,, ㅠㅠ
그럴때마다 했던 작업들을 모조리 날려버리고 새로 작성한다면 너무 끔찍하겠죠?
지금은 몇 줄 안되는 코드겠지만 수 백, 수 천 줄로 작성된 코드를 다 날리고 처음부터 하게되면,, 상상이 가시나요 ㅎㅎ
무언가 실수 했을 때 깃을 통해 어떻게 원하는 시점으로 돌아갈 수 있는지에 대해
좀더 알아보시면 좋을거 같아요!! 꽤나 어려울거예요!! 저도 어렵습니다 😫

---

### 순서도
순서도의 배경이 검은색이여서 그런가 글씨가 잘 보이지 않아요 ㅠㅠ
제가 다크모드로 사용해서 그럴수도 있어요 !
그리고 순서도에 대한 의문점도 있는데요!!
Body를 만드는 것과 Bar를 만드는 구조는 비슷하니 하나의 함수로 예로들어 말씀드릴게요!
makeIcecreamBody() 함수가 호출되면 어떠한 과정도 거치지 않고 바로 *를 출력할까요??
무언가 조건식이 먼저 나오고 내부 실행문이 실행될거라 생각해요!! 원이의 생각은 어떠신가요?

---

코멘트에 대해 생각해보시고, 조금의 수정 후 다시 PR 보내주시면 검토 후 머지 진행하겠습니다!

2022-04-15 16:01 UTC, jaemuYeo requested changes
고생 많으셨어요 원이!! 👍
아직 Xcode도 그렇고 문법도 그렇고 많이 낯설었을텐데
이번 스텝을 통해 조금 친해지셨나요??
너무 잘 따라와주고 계셔요!! 멋집니다 ㅎㅎ 😀
몇몇 수정해야할 사항들이 있어서 코멘트를 통해 전달드릴게요~

---

### 코드

함수의 네이밍도 잘 지어주셨고, 두 개의 함수 모두 잘 작동되게 구현하셨네요!!
다만 애플이 제안하는 Swift Design Guidelines에서 띄어쓰기는 어떻게하고 있는지
숙지해주시고 코드 수정해주셨으면 좋겠습니다!!
잘 모르겠다면 캠프사이트의 학습자료를 참고하셔도 좋아요!

`고칠 부분 = 중괄호`
`고칠 부분 print("\(xdan)x\(i)=\(xdan*i)")`

금방 캐치하실 거예요 걱정마세요!

---

### 커밋메시지
디스코드에서 나눴던 대화 중 커밋 컨벤션에 대해 기억하시나요??
다음 스텝에서는 참고하셔서 커밋해주시면 좋을거같아요!!
이번에 수정하시면서 아이스크림 만드는 함수와 구구단 구현 함수의 파일을 나눠보고
어떻게 커밋하면 좋을지 고민하고 PR 제출해주세요!!
해결이 안되시면 언제든 질문 주세요 😊

---

### 레포지터리 삭제에 대하여

종종 여러 작업들을 실수하는 경우가 발생한답니다!! 너무나 당연한 일이예요,, ㅠㅠ
그럴때마다 했던 작업들을 모조리 날려버리고 새로 작성한다면 너무 끔찍하겠죠?
지금은 몇 줄 안되는 코드겠지만 수 백, 수 천 줄로 작성된 코드를 다 날리고 처음부터 하게되면,, 상상이 가시나요 ㅎㅎ
무언가 실수 했을 때 깃을 통해 어떻게 원하는 시점으로 돌아갈 수 있는지에 대해
좀더 알아보시면 좋을거 같아요!! 꽤나 어려울거예요!! 저도 어렵습니다 😫

### 순서도

순서도의 배경이 검은색이여서 그런가 글씨가 잘 보이지 않아요 ㅠㅠ
제가 다크모드로 사용해서 그럴수도 있어요 !
그리고 순서도에 대한 의문점도 있는데요!!
Body를 만드는 것과 Bar를 만드는 구조는 비슷하니 하나의 함수로 예로들어 말씀드릴게요!
makeIcecreamBody() 함수가 호출되면 어떠한 과정도 거치지 않고 바로 *를 출력할까요??
무언가 조건식이 먼저 나오고 내부 실행문이 실행될거라 생각해요!! 원이의 생각은 어떠신가요?

---

코멘트에 대해 생각해보시고, 조금의 수정 후 다시 PR 보내주시면 검토 후 머지 진행하겠습니다!

2022-04-18 12:18 UTC, One-E12 commented
잼킹이 말씀해주신대로 수정해봤는데 괜찮은 커밋이었는지, 괜찮은 중괄호 수정이었는지 모르겠어요 🧐

--- 
commit을 docs: 이렇게 한건 새로운 코드를 작성한게 아니라서, feat으로 시작하지 않았는데 이렇게 작성하는게 맞는걸까요??🤔

만약 빼빼로 과제를 하게 된다면,
빼빼로 바 만드는 함수를 구현하고, 커밋하는 경우에는 feat: 빼빼로 바 만들기 완성 

이렇게 작성하는게 맞을까요?? 

+ 야곰의 라이브 세션에서도 커밋에 대한 이야기를 많이 해주셨는데 역시나 아직 너무 어렵네요 😖

--- 
<img width="645" alt="순서도_아이스크림만들기" src="https://user-images.githubusercontent.com/97447840/163806519-64936cde-e08f-4ef3-9dad-d248576caf04.png">

그리고 새벽에 잼킹에게 보냈었던 순서도 친구를 프로그램으로 다시 만들었답니다! 

답은 없다고 하셨지만, 늘 그렇듯 뭔가 괜찮네요! 라는 답을 들어야 안심이 되는 건 어쩔 수 없나봐요. 뭔가..., 확인 받아야 제출할 수 있을 것 같은 그런 느낌이요!

아직도 순서도 그리기는 너무 어렵고, 제 생각을 그림과 글로 표현한다는게 어렵지만, 다음 step 3 미션에서도 열심히 그려보려고 해요!!

코딩도 순서도도... 많이 해봐야 느는거겠죠? 🐥

--- 

사실 첫 주를 보내고 사람들은 한 15년 저 깊은 코딩 바다에서 살아온 어른 거북이🐢들이면, 저는 이제 막 코딩 세계에 태어난 아기거북이 같은 느낌이라 힘들었는데, 잼킹의 도움으로 자신감이 채워졌어요!  물론 아직 거북이는 맞지만요! 


혹시 더 수정해야 할 부분이 있다면 수정해서 또 보낼게요 잼킹!

2022-04-18 16:03 UTC, jaemuYeo requested changes
띄어쓰기 한번 다시 확인 부탁해요!

2022-04-18 16:08 UTC, One-E12 commented
정말 한 줄 한 줄 신경써야 한다는 걸 느꼈어요 잼킹...! 

함수() 뒤 { 띄어쓰기} 꼭 기억할게요... 확실히 코드를 덮어씌워보니까 어디가 수정됐는지 보여서 확 느껴졌습니다:)

2022-04-18 16:12 UTC, jaemuYeo reviewed
스텝2 고생많으셨어요!! 
함수 뿐만 아니라 또 다른 어떤곳에서도 띄어쓰기 해야하는 곳도 있고,
줄바꿈(개행) 또한 신경을 써야해요!!
붙여쓴다고 에러가 발생하지는 않지만 가독성을 위한 약속?같은거라 생각하시면 돼요!!
이번 스텝은 여기서 머지하겠습니다!
다음 스텝에서 만나요 😀

2022-04-18 16:13 UTC, merged