Week1 [STEP 2] Shube24
yagom-academy/swift_starter-week1 pull request #84
Opened 2022-04-17 18:05 UTC by Shube24

@yeahg-dev 님 안녕하세요!
주말이 끝나고 평일이 다가왔네요,,  ~~아악~~
STEP2 를 주말동안 여러가지 방법들 많이 생각해보고 많이 해보고 하느라 이렇게 늦어졌는데
꼭 PR까지 하고 끝내겠다는 집념..으로 해냈습니다,,

1. 우선으로 함수 안에 for-in문으로 먼저 해보자라는 생각으로 만들어봤습니다.

2. for-in문 사용하지 않는 변수는 와일드카드로 쓰라고 경고(?)메시지 나와서 와일드카드로 변수 지정했습니다.

3.  상수를 이용한 코드도 만들어봤는데 이름지정이 시간이 많이 걸리더라구요.. ~~억지로 만들긴했지만~~ 
   코드 첨부 드리니 이것도 같이 봐주시면 감사하겠습니다.
```
func hardIceCream() {
    let hardWidth = 11
    let iceCreamHeight = 8

    for _ in 1...iceCreamHeight {
        for _ in 1...hardWidth {
            print("*", terminator: "")
        }
        print("")
    }
}

hardIceCream()

func WoodenStick() {
    let stickHeight = 4
    let widthOftheStick = 4

    for _ in 1...stickHeight {
        for _ in 1...widthOftheStick {
            print("", terminator:" ")
        }
        print("| |")
    }
}

WoodenStick()
```

2022-04-18 13:21 UTC, yeahg-dev requested changes
안녕하세요 슈비님!
불타는 집념! 정말 멋진데요??😎
아이스크림을 그리는 두가지 함수를 잘 분리해서, 만들어주셨네요
아이스크림 모양도 완벽합니다👍

### 🚀 칭찬드리고 싶은 점
- 아이스크림의 각 부분을 그리는 함수 2개를 각각 반복문을 훌륭하게 활용하셔서 구현해주셨어요💯
- 카멜케이스 표기법을 잘 지켜주셨어요!
- 구체적인 네이밍으로 상수가 어떤 역할을 하는지 이해가 쉬웠습니다
- 순서도의 기호를 공부하시고, 알맞은 기호를 올바르게 선택해주셨어요! 

첨부해주신 상수를 이용한 버전도 확인했습니다

오래 생각하신 만큼 네이밍도 아주 직관적이라 좋습니다.
(다만,`widthOftheStick`은 현재 함수에서의 역할과 의미가 좀 다른것 같아요)

상수를 이용한 버전과 아닌 버전, 슈비님은 각각 어떤 점이 좋은 것 같나요?
한번 생각해보시면 좋을 것 같습니다!

---

### 💡 전반적 리뷰

1.  아래 요구사항을 구현해주세요
> Clone 받은 폴더 내부에 Xcode 프로젝트를 생성합니다.
    (MacOS 항목의 Command-Line-Tool을 선택해주세요.)

현재 스타터위크캠프 폴더에 코드가 작성되어있습니다.
새로운 Xcode프로젝트를 생성해서, 그 안에 작성해주세요

2. 순서도
작성해주신 코드의 흐름과 순서도의 흐름이 맞지 않습니다.

아래 사항을 생각하며 수정을 해보시면 좋을 것 같습니다😊
- 현재 count의 첫 시작 숫자는 몇일까요? 
  이에 대한 정보도 추가해주어야 몇 번 반복이 되는지 파악할 수 있습니다.
- 아이스크림 면과 스틱을 그리기위해 이중 반복문(중첩루프)를 사용해주셨습니다
  중첩루프 순서도에 대해 검색해보시면 힌트를 얻으실 수 있을거에요
- 입력/출력에 대한 기호도 고려해봅시다.

3. 커밋 단위에 대한 고민도 한 번 해볼까요?
커밋은 언제 하는걸까요?
커밋단위에 대한 정답은 없지만, 커밋을 왜 하는지에 대해 생각해보면 자신만의 커밋 단위 기준을 세우는데 도움이 될거라 생각합니다.

---
코드에 대한 리뷰는 아래 댓글에 남겨두었으니 확인부탁드립니다.

저의 리뷰가 절대적인 정답은 아닙니다!
그러므로 리뷰에 대한 궁금점이나 의문점이 있으시면 언제든 PR의 코멘트나 메시지 주세요~
함께 이야기해보아요😊

수정 완료되면 재리뷰 요청주세요!

2022-04-18 13:27 UTC, yeahg-dev commented on CodeStarterCamp_Week1/main.swift
> +}
반복문의 범위를 명시하는 방법엔 다양한 선택지가 있습니다.
알고 계셨나요?👀
이와 관련하여 아래 공식문서를 읽어보는 것도 좋을 것 같습니다~
https://docs.swift.org/swift-book/LanguageGuide/BasicOperators.html#ID73

2022-04-18 17:35 UTC, Shube24 commented on CodeStarterCamp_Week1/main.swift
> +}
해당 링크에서 읽어봤습니다😄
제가 사용한 반복문 범위 연산자는 닫힌 범위 연산자(Closed Range Operator
)를 사용했구요.
```
for i in 0..<count {
    print("Person \(i + 1) is called \(names[i])")
}
```
와 같은 범위 연산자는 반 개방 범위연산자 (Half-Open Range Operator)

```
for name in names[2...] {
    print(name)
}
```
와 같은 범위 연산자는 단측 범위 연산자 (One-Sided Ranges) 
이 세가지 읽어 보았습니다 :)

2022-04-18 17:35 UTC, Shube24 commented on CodeStarterCamp_Week1/main.swift
> +}
해당 링크에서 읽어봤습니다😄
제가 사용한 반복문 범위 연산자는 닫힌 범위 연산자(Closed Range Operator
)를 사용했구요.
```
for i in 0..<count {
    print("Person \(i + 1) is called \(names[i])")
}
```
와 같은 범위 연산자는 반 개방 범위연산자 (Half-Open Range Operator)

```
for name in names[2...] {
    print(name)
}
```
와 같은 범위 연산자는 단측 범위 연산자 (One-Sided Ranges) 
이 세가지 읽어 보았습니다 :)

2022-04-18 18:00 UTC, Shube24 commented
리뷰해주신 부분 이후 수정한 부분 커밋하였습니다.

커밋 단위를 생각해봤는데, 저는 커밋을 중요한 정보, 자료를 기록하고 싶을때 바로 찍어서 저장소에 저장하는 스크린샷으로 생각하고 있습니다.
아직은 Git과 커밋에 익숙하진 않아서 커밋을 언제 해야한다, 저만의 커밋 단위 기준은 정해놓진 않았습니다.앞으로 과정을 통해

2022-04-18 18:00 UTC, Shube24 commented
리뷰해주신 부분 이후 수정한 부분 커밋하였습니다.

커밋 단위를 생각해봤는데, 저는 커밋을 중요한 정보, 자료를 기록하고 싶을때 바로 찍어서 저장소에 저장하는 스크린샷으로 생각하고 있습니다.
아직은 Git과 커밋에 익숙하진 않아서 커밋을 언제 해야한다, 저만의 커밋 단위 기준은 정해놓진 않았습니다.앞으로 과정을 통해

2022-04-19 06:42 UTC, yeahg-dev commented on CodeStarterCamp_Week1/main.swift
> +}
좋습니다!😃
전 상수를 사용해서 위 반복문에서 쓰이는 숫자가 어떤 의미인지 명시적으로 보여주는 것도 좋다고 생각해요.
코드를 보는 사람입장에서 그냥 8이라고 하면 코드를 실행하기 전까지는 이것이 아이스크림의 높이인지 넓이인지 생각해내기가 좀 더 어렵겠죠??
좀 더 확장해서 숫자, 문자열과 같은 리터럴의 경우는 변수로 정의해서 사용하는 것이 가독성과 유지보수 측면에서 좋다고 생각합니다

2022-04-19 07:19 UTC, yeahg-dev requested changes
리뷰해주신 내용대로 잘 고민해서 수정해주셨어요👍

커밋 단위도 슈비님 말씀처럼 스스로 고민해보고 정해가면 된다고 생각해요!
그리고 카르마 스타일도 공부해보시고 적용해보신것 아주 좋아요😃
(아 그리고, 커밋 타이틀에 type에는 이 커밋의 유형을 적어줘요.
슈비님의 이번 커밋의 경우는 리팩터링을 해주셨으니 "Recator: 코드 순서 수정(예를들면)"정도로 작성할 수 있겠네요! )

그런데 머지에 앞서 순서도가 아직 코드와 맞지 않아요
예를 들면, makeHardIceCream()의 순서도대로 실행을 하면 아래와 같이 출력되게 되어요
```swift
***********
********
```
슈비님의 코드는 그림의 한줄을 그리기 위한 코드가 바깥 루프에 의해서 반복되는 구조인데, 
순서도는 `*을 출력`이 11한번 반복되고 루프에서 나와서 `*******출력`을 한 번하고, 아무것도 실행하지 않는 루프를 8번 반복하고 있어요

이중 반복문 표현이 어렵다면 우선 외부 반복문 안의 코드를 하나의 실행블록으로 간주하고 그려보는 건 어떨까요? 

for문에 대한 순서도를 그리는 방법을 저도 찾아보았더니 [참고 블로그](https://www.memoengine.com/blog/for%20%EB%AC%B8%20%EC%88%9C%EC%84%9C%EB%8F%84%20-%20for%20%EB%AC%B8(for%20loop)%20%EC%88%9C%EC%84%9C%EB%8F%84(flowchart)/)와 같이 여러가지 방법이 있더라구요. 참고해보시면 좋을 것 같습니다.

순서도 한 번 다시 고민해보시고 수정후 메시지 주세요!

2022-04-20 04:43 UTC, Shube24 commented on CodeStarterCamp_Week1/main.swift
> +func iceCreamStick() {
수정하였습니다 :)

2022-04-20 05:00 UTC, yeahg-dev approved these changes
순서도 수정 수고많으셨습니다~!
이번 스텝이 순서도와 좀 더 친해지는 계기였음 좋겠네요😊

스텝2 수고많으셨어요!
스텝3에서 뵐게요🚀

2022-04-20 05:00 UTC, merged