Week1 [Step3] 윤세영
yagom-academy/swift_starter-week1 pull request #87
Opened 2022-04-18 07:40 UTC by ssyoun4092

@oksunwoo 

merge 단계에서 충돌이 일어나는 것을 해결하느라 마지막 여러개 커밋들이 충돌 관련된 커밋입니다.
로컬 리포지토리에서 merge를 하고 push하는 것으로 방향을 틀어서 PR하려고 했습니다. 그래서 step3에 있는 파일을 제 로컬 리포지토리로 pull해서 덮어씌우려고 했더니 충돌이 발생했습니다.
파일 내부에

```swift
<<<<HEAD

=======
```
등의 알 수 없는 단어들이 생겼는데 구글링 해보니 오히려 충돌을 수정할 수 있게 도와주는 좋은 코드임을 알게되었습니다.

수정할건 수정하고 push를 하니 정상적으로 push가 되었습니다만.. 여전히 정확히 어떤 상황이었는지를 이해하기가 어렵네요ㅠ 
조금 더 공부해보겠습니다!

---
Step3 과제 내용
> ## 코드 내용

### 길이(Int)에 따른 막대(빼빼로 손잡이)를 그리는 함수
```swift
func makePeperoStick(stickHeight: Int) {
    for _ in 1...stickHeight {
        print(" | | ")
    }
}

makePeperoStick(stickHeight: 5)
````
위의 코드로 구현하였습니다. stickHeight를 매개변수로 받아, 그 숫자만큼 스틱을 print하게 했습니다.

### 몸통(String), 토핑(String)을 매개변수로 받아 토핑과 몸통을 그리는 함수
```swift
func whatTypePepero(body: String, topping: String) {
    print("\(topping)\(body) ")
    print(" \(body)\(topping)")
}

whatTypePepero(body: "***", topping: "&")
````
빼빼로 몸통 종류와 토핑 종류를 매개변수로 받아 두 줄을 하나의 세트로 간주하고 print했습니다.
1. 보다 직관적인 함수 이름이 안떠올랐습니다. 
2. 변수 / 함수 이름을 직관적으로 지을 수 있는 노하우가 있다면 알고 싶습니다!

### 길이(Int)에 따라 몸통을 그리는 함수
```swift
func peperoBodyLength(bodyLength: Int, body: String, topping: String) {
    for _ in 1...(bodyLength / 2) {
        whatTypePepero(body: body, topping: topping)
    }
}

peperoBodyLength(bodyLength: 10, body: "***", topping: "&")
````
1. bodyLength로 매개변수를 받지만, body를 프린트하는 함수 안에서는 두줄을 프린트하기에 bodyLenght에서 2를 나누어 for문을 실행하였습니다.

> 코드 질문
1. 제가 작성한 코드가 직관적으로 보이는지 알고 싶습니다. 함수이름 등을 보았을 때 무슨 기능을 하고 있는 것인지 바로 알 수 있는지 알고 싶습니다.
2. 보다 더 효율적으로 함수를 구현할 수 있는 방법이 있는지도 알고싶습니다!

2022-04-18 10:46 UTC, oksunwoo requested changes
전반적으로 잘짜신 코드같습니다.
한눈에 보기에도 깔끔하네요!

메서드 이름짓는 부분만 잘 해결하면 될 것 같은데, 제가 첨부해드리는 문서 한번 천천히 살펴보시고 고민한번 해보시길 추천드립니다! detail누르면 예시가 나와요!
https://www.swift.org/documentation/api-design-guidelines/


그리고 요구사항이 출력이랑 조금 다르네요!
<img width="691" alt="스크린샷 2022-04-18 오후 6 55 49" src="https://user-images.githubusercontent.com/55880539/163797688-8a02d3b1-eb86-4445-a339-ecba241923c4.png">

차이점 한번 찾아보시고 수정해서 다시 PR 주세요
읽기에는 정말 깔끔한 코드였습니다.

2022-04-18 10:46 UTC, oksunwoo commented on CodeStarterCamp_Week1/main.swift
> +func makePeperoStick(stickHeight: Int) {
읽었을때 Stick 이 중복되는 것 같네요! 
makePeperoStick(height: Int)가 조금 더 자연스러운것 같은데 어떻게 생각하시나요?

2022-04-18 10:46 UTC, oksunwoo commented on CodeStarterCamp_Week1/main.swift
> +func whatTypePepero(body: String, topping: String) {
메서드명에서 고민을 하신거같은데, 남들이 읽었을때 무슨 역할을 하는 메서드인지 딱 알수있게 해놓으면 좋을 것 같아요~
예를 들면 계산기 앱을 만든다고 가정했을때, func add(number: Int)와 같은 느낌이면 메서드내부를 보지않고도 유추가 가능하겠죠?
그러면 나중에 코드가 1000줄, 10000줄이 넘어갈 정도로 긴 경우에도 덧셈 하는곳을 바꾸기 위해서 일일이 메서드 내부를 살피는 일을 하지 않아도 될거같지 않나요? 제가 첨부해드린 api Design Guide 한번 천천히 읽어보시고, 한번 고민해보세요

2022-04-18 10:46 UTC, oksunwoo commented on CodeStarterCamp_Week1/main.swift
> +print("")
세영님께서 처음에 코드를 메인에 작성하지 않으시고, 다른 곳에다가 작성을 하셔서 코드가 작동하지 않는 현상이 발생했었죠!
지금 이 실행이 되는 코드만 메인으로 분리해보는 것은 어떨까요? 아래처럼 말이죠

<img width="229" alt="스크린샷 2022-04-18 오후 7 26 02" src="https://user-images.githubusercontent.com/55880539/163795513-7b1baa67-e5f9-4c69-9b63-4120f7dcc8bd.png">

이제 파일분리까지 경험해보시는거에요! 그리고 내가 작성한 코드는 메인에서 동작한다는 것까지 챙겨가시면 더 좋구요!

2022-04-18 10:46 UTC, oksunwoo commented on CodeStarterCamp_Week1/main.swift
> +func peperoBodyLength(bodyLength: Int, body: String, topping: String) {
메서드 명이 마치 변수 또는 상수명처럼 느껴지네요!
메서드는 영어 문장처럼 사용할 수 있도록 해야한다고 guide line에 있는데 예시도 한번 읽어보시는 것을 추천드릴게요!

2022-04-19 05:37 UTC, ssyoun4092 reviewed
> 요구사항과 출력사항이 다른 부분을 해결했습니다.
+ 빼빼로 몸통 사이사이, 스틱 사이사이에 빈 공간이 있는 걸로 생각하고 수정했는데 맞는지 모르겠습니다!

> 전반적인 메서드 명을 수정하였습니다.
+ 링크 걸어주신 애플 가이드라인을 참고하였고, 함수 이름을 읽었을 때 보다 자연스럽게 수정했습니다! 훨씬 나은거 같아요!

> 실행이 되는 코드만 메인으로 분리하라고 하셨는데.. Class를 사용하는거 맞나요?
+ 아카데미에서 아직 class를 배우지 않아서 이걸 사용하는게 맞는지 잘 모르겠습니다...(저도 아카데미 참여하기 전에 잠깐 독학했을 때 얕게 배운거라 class를 이렇게 사용하는건지 확실히 잘 모르겠습니다!)
+ 다른 방법이 있었다면 알려주시면 감사하겠습니다!

2022-04-20 06:09 UTC, oksunwoo requested changes
클래스를 벌써..! 적용하셨네요
사실 제 의도는 이게 아니였답니다! 아직 진도상으로 클래스 안배우신 걸로 아는데 검색하고 적용하시는데 힘드셨겠어요... 고생하셨습니다.

제가 의도한 바는 세영님께서 작성하신 step2 파일 기준으로
`drawIcecreamTop()` 이랑 `drawIcecreamStick()` 이 두문장을 main으로 옮겨작성해보시면 무슨 느낌인지 아실 것 같아요!

2022-04-20 06:09 UTC, oksunwoo commented on CodeStarterCamp_Week1/step3.swift
> +            print("")
이 공간은 필요없을 것 같네요!

2022-04-20 06:09 UTC, oksunwoo commented on CodeStarterCamp_Week1/step3.swift
> +}
가장 메인이 되는 메서드는 makePepero 처럼 보이는데요!
메서드의 순서를 변경함으로써도 가독성을 개선할 수가 있답니다!
보통 코드는 위에서 아래로 읽잖아요. 가장 메인이 되는 함수를 가장 위 또는 아래에 두고, 사용된 메서드들 순서대로 메서드 위치를 변경해보는 것은 어떨까요?
```swift
func English() {
a()
b()
c()
}
func a() {}
func b() {}
func c() {}
```
이와 같은 방식으로 말이죠! 그러면 조금 더 읽기 쉬워지지 않을까요?

2022-04-20 06:30 UTC, ssyoun4092 reviewed
+ 가독성을 위한 함수 배치 순서 변경하였습니다!
+ step3.swift에서 불필요한 class 삭제하였습니다!
+ main.swift에서 클래스를 통해 호출했던 함수를 단순히 함수만 호출하는 것으로 변경하였습니다!

2022-04-20 06:31 UTC, ssyoun4092 commented on CodeStarterCamp_Week1/step3.swift
> +}
넵!
makePepero 메서드를 맨 위에 두고, 차례대로 빼빼로 바디, 빼빼로 스틱을 만드는 메서드 순으로 정리하였습니다.
확실히 보기 더 편한것 같아요!

2022-04-20 06:32 UTC, ssyoun4092 commented on CodeStarterCamp_Week1/step3.swift
> +            print("")
넵! 삭제하였습니다!

2022-04-20 12:09 UTC, oksunwoo reviewed
세영님 혹시 코드 돌려보셨을까요? 빨간색 에러가 하나 보이는데, 확인부탁드립니다~

2022-04-20 12:09 UTC, oksunwoo commented on CodeStarterCamp_Week1/main.swift
>  //peperoBodyLength(bodyLength: 10, body: "***", topping: "&")
코드에서 불필요한 주석은 남기지 않습니다~

2022-04-20 12:45 UTC, ssyoun4092 reviewed
+ 불필요한 주석 제거하였습니다!
+ 에러 수정하였습니다!

2022-04-20 12:46 UTC, ssyoun4092 commented on CodeStarterCamp_Week1/main.swift
>  //peperoBodyLength(bodyLength: 10, body: "***", topping: "&")
넵!!

2022-04-20 12:51 UTC, merged