Week1 [Step3] som
yagom-academy/swift_starter-week1 pull request #88
Opened 2022-04-18 09:27 UTC by jsa0224

@Jager-yoo

## 실수한 부분
Staging Area에서 최근 커밋을 삭제한다는 게... 전에 커밋하던 것도 싹 삭제가 되어서 
다시 브렌치에서 pull하고 커밋한거라 **첫번째의 빼빼로 코드 추가**에서는 전에 있던 과제 전부가 올라와 있으니 
스킵해주시면 감사하겠습니다...ㅠㅜ

## 궁금한 부분 
1.
```Swift
 peperoBodyHeight = 10, choko = "***", sprinkle = " ", peperoStickHeight = 4
```
이 부분에서 변수를 구분하기 위해  ','를 기입하였는데 세미콜론(;)을 기입하라는 오류가 나왔습니다.
스위프트에서는 세미콜론을 자바 언어처럼 끝마다 ;를 사용하지 않아도 되었었는데, 변수를 한 줄로 나열할 때 필요한 요소인가요?

2. main.swift 파일에 대하여
제가 이번 과제에서 제일 어려웠던 부분인데요. 구글에서 찾아본 결과, 제가 나름대로 해석해본다면! 
main은 상위의 개념이고 다른 스위프트 파일은 하위의 개념인가요?
main이 있는 상태에서, 다른 스위프트 파일에 함수를 호출했더니 오류 메세지가 뜨더라고요. 
그래서 코드 작성만 스위프트 파일에서 하고 호출만 main에서 하니 오류가 사라졌습니다.
제가 이해한 것이 맞을까요...?

2022-04-18 12:30 UTC, Jager-yoo commented
안녕하세요 솜!
Step 3 제출하느라 수고 많으셨습니다. 😄 

질문해주신 것 먼저 답변 드리고 → 코드 단위로 리뷰 달아두겠습니다!

### ✅ 여러 개의 변수 할당을 한 줄에서 하는 법

- 솜은 `글로벌 변수`를 여러 개 생성하신 뒤, 메서드를 호출하기 직전에 변수들의 값을 변경해주는 코드를 작성하셨습니다.
- 이때, 보여주신 코드처럼 `콤마(,)`를 사용하니 빨간색 `컴파일 에러`가 떴다고 하셨는데요, 이 경우 콤마 자리를 `;` 로 변경하시면 작동할 겁니다.
- 다만, 일반적으로 변수(var)를 바꾸는 경우, 한 줄에 몰아서 하기 보다는, `줄바꿈`으로 구분해가며 가독성을 높이는 스타일이 선호됩니다.

```swift
// 변수 할당을 한 줄에 몰아서 사용하고 싶다면...
peperoBodyHeight = 10; choko = "***"; sprinkle = " "; peperoStickHeight = 4

// 일반적으로는 하나씩 나열해서 가독성을 높입니다.
peperoBodyHeight = 10
choko = "***"
sprinkle = " "
peperoStickHeight = 4
```

### ✅ main.swift 파일에 대해

아~ 주 좋은 질문입니다. 👍🏻 
우선, main 이 상위 개념이고 다른 스위프트 파일이 하위 개념이냐고 질문 주셨는데요.
제 생각은... 반은 맞고 반은 틀린 것 같습니다.

제가 말씀드리고 싶은 건, `main` 키워드는 🟢`entry-point`라고 생각하시면 된다는 것입니다.
해석하면 뭐죠? → '시작점' 입니다.
그니까, 우리가 막 파일도 여러 개 만들고, 메서드도 잔뜩 만들지만, 결국 컴퓨터에게는 `"어디부터 시작할지"` 를 알려줘야 하겠죠?

`main.swift` 파일은, 지금 작업하고 계시는 [Xcode Command Line Tool] 에서의 `시작점`입니다.
컴퓨터는 이 파일의 첫 번째 줄부터~ 아래로 순서대로 읽어나가면서 메서드를 호출하는 것이죠. ㅎㅎ
이 과정에서 main.swift 파일에서 정의되지 않은 메서드나 타입을 만나면? → 다른 파일에 있는지 검색해보고 불러오는 것입니다.

좀 더 쉽게 비유를 들어보자면, `main.swift` 파일은 요리를 위한 `도마`, 다른 파일들은 `음식 재료가 담긴 상자` 정도로 생각해볼 수 있겠습니다. 
요리를 만들기 위해선, 음식 재료들을 `상자에서 꺼내서` 도마 위로 가져와야겠죠? 🧑🏻‍🍳
이때, 재료를 상자에서 꺼내지 않고, 그 안으로 🔪 칼을 집어 넣어서 손질을 한다면, 위험하고 불편할 겁니다. 😅 
그래서 스위프트에서도 main.swift 가 아닌 파일에서의 메서드 호출을 다 막아둔 것입니다.

[이 링크](https://www.raywenderlich.com/511-command-line-programs-on-macos-tutorial)의 캡처 부분을 참고해보셔도 좋겠습니다. 👍🏻 

<p align="left"><img src="https://user-images.githubusercontent.com/71127966/163808214-b4725cd2-8b2d-41c0-84cc-f99bd16c9457.png" width="80%"></p> 

현재 공부하고 계신 [Command Line Tool]에서는 화면(UI)이 없지만, 나중에 `UIKit`, `SwiftUI` 같이 `UI가 있는 프레임워크`를 공부하시게 된다면, `main` 키워드를 다시 만나실 수 있을 겁니다!
거기에서는 main.swift 라는 파일은 없지만, `@main`이라는 키워드가 사용됩니다.
늬앙스는 똑같습니다. 프로그램은 여기서 시작한다는 겁니다! ㅎㅎ

|UIKit|SwiftUI|
|:-:|:-:|
|<img src="https://user-images.githubusercontent.com/71127966/163807702-ee303b49-835b-4713-b173-1a506835dd16.png">|<img src="https://user-images.githubusercontent.com/71127966/163807868-51fc27ce-4489-4c95-a06f-54626a02ec10.png">|

2022-04-18 12:45 UTC, Jager-yoo requested changes

2022-04-18 12:45 UTC, Jager-yoo commented on CodeStarterCamp_Week1/MakePepero.swift
> +}
아무 곳에서나 접근할 수 있고, 변경할 수 있는 `글로벌 변수`를 통해 빼빼로를 print 하기 보다는
메서드의 파라미터(매개변수)를 통해 필요한 요소를 입력 받아서, 독립적으로 빼빼로를 print 해주는 방식이 안전할 것 같습니다. 👍🏻 

그리고 메서드의 이름은 `소문자(lowerCamelCase)`로 시작하는 게 맞습니다!
나중에 만들어볼 `타입`들의 이름을 `대문자(UpperCamelCase)`로 시작합니다. 😄 

아래 suggestion 에서 어떤 것이 변경됐는지 (네이밍, 파라미터 이름 등) 잘 살펴보시고
어떤 장점이 있을까 고민해보시면 좋겠습니다!

```suggestion
func makeNormalPepero(bodyHeight: Int, choko: String, stickHeight: Int) {
    for _ in 1...bodyHeight {
        print(" ", choko, separator: "")
    }
    
    peperoStick(height: stickHeight)
}

func makeToppingPepero(bodyHeight: Int, choko: String, sprinkle: String, stickHeight: Int) {
    for _ in 1...bodyHeight/2 {
        print(sprinkle, choko, " ", "\n", " ", choko, sprinkle, separator: "")
    }
    
    peperoStick(height: stickHeight) // 스틱을 만드는 메서드는 메서드에 미리 포함시켜서 놓칠 일이 없도록 합니다
}

func peperoStick(height: Int) {
    for _ in 1...height {
        print(" | |")
    }
    
    print("-----구분선-----") // 이건 제가 그냥 넣어본 겁니다. 빼빼로 구분해주려고!
}

// main.swift 에서는 최대한 `정의`보다는 `호출`위주로 하기 위해, 이 메서드도 여기서 미리 정의해두면 어떨까요?
func compeletePeperos() {
    makeNormalPepero(bodyHeight: 10, choko: "***", stickHeight: 4) // 일반 빼빼로
    makeToppingPepero(bodyHeight: 12, choko: "***", sprinkle: "&", stickHeight: 4) // & 토핑 빼뺴로
    makeToppingPepero(bodyHeight: 12, choko: "***", sprinkle: "#", stickHeight: 4) // # 토핑 빼빼로
    makeNormalPepero(bodyHeight: 6, choko: "|0|", stickHeight: 4) // 누드 빼빼로
    makeToppingPepero(bodyHeight: 10, choko: "🟫", sprinkle: "⭐︎", stickHeight: 4) // 네모 빼빼로
}
```

2022-04-18 12:45 UTC, Jager-yoo commented on CodeStarterCamp_Week1/main.swift
> +CompeletePepero()
빼빼로 생산에 필요한 변수들은 모두 `메서드의 파라미터`로 받는 방식으로 변경했으니
여기에 정의해둔 메서드들은 전부 삭제해도 되겠죠! 👍🏻 

```swift
compeletePeperos() // 이거 하나만 main.swift 에 있어도 됩니다.
```

2022-04-18 12:45 UTC, Jager-yoo commented on CodeStarterCamp_Week1/main.swift
> +>>>>>>> 6585929338347c65a42f9ff4d212310d27f3943d
과거 코드는 없애고, conflict 나는 건 해결하거나 덮어씌울 수 있게 해보시면 좋겠습니다!
이번에 `수정 커밋`하면서 한 번 시도해보세요! 😄

2022-04-19 01:31 UTC, jsa0224 commented
@Jager-yoo 
어제 늦은 시간인데도 불구하고 컨플릭트 오류 해결 도와주셔서 다시 한 번 감사드립니다:)
아무래도 pull하면서 생겨난 컨플릭트 오류인 거 같아 기억을 거슬러 올라가보기 시작했어요.

- pull을 하면서 생겨났던 오류
Your local changes to the following files would be overwritten by merge -> [해당 해결방법](https://goddaehee.tistory.com/253)<br> untracked working tree files overwritten -> [해당 해결방법](https://devonaws.com/git/git-pull-%EB%AA%85%EB%A0%B9-%EC%8B%9C%EC%97%90-untracked-working-tree-files-overwritten-%EB%82%98%EC%98%AC-%EB%95%8C/)
(혹시 이 부분에서 문제였을지도 모른다는 생각에 한 번 올려봅니다.)

제 원격 저장소의 commit 기록이 다 날라갔던 상태라 해당 방법들로 pull 오류를 해결하고 제 브렌치에서 pull을 진행했죠!
현재 제 컴퓨터에 있던 Week 1 프로젝트의 파일에서는 *아이스크림 스위프트 파일, 빼빼로 스위프트 파일, 메인 스위프트 파일* 이렇게 3개의 파일이 들어있었던 상태였습니다.
하지만 제가 pull해온 Week 1 프로젝트 파일에서는 메인 스위프트 파일(아이스크림 코드가 있는) 하나였죠.

기존의 Week 1 프로젝트의 파일과 제 브렌치에서 pull해온 Week 1 프로젝트의 파일이 그렇게 충돌이 일어나 컨플릭트 오류가 생겨난 것 같습니다. 아무리 생각해도 이 방법 아니고서야... 이런 오류가 일어나지 않을 거 같아요.

이런 상태로 git add를 통해 *아이스크림 스위프트 파일, 빼빼로 스위프트 파일, 메인 스위프트 파일* 3개의 파일이 들어있는 파일만 .xcodeproj 파일을 포함하지 않은 채 따로 커밋을 진행했습니다.

그래서 .xcodeproj 파일을 여셨을 때, 컨플릭트 오류와 함께 아이스크림 파일, 빼빼로 파일이 포함되지 않았던 이유였던 것 같습니다...

제가 코딩 초보자라 어떻게 설명하면 좋을지... 이게 맞는지 잘 모르겠지만 제 생각을 예거에게 공유하고 싶었습니다!

2022-04-19 03:46 UTC, Jager-yoo commented on CodeStarterCamp_Week1/MakePepero.swift
> +}
솜~! 빠르게 수정해주셨군요! 👏🏻
마지막으로 한 번만 수정해보죠!

- 먼저, 각각의 메서드 정의 코드 사이에는 `여백(빈 엔터)`이 한 줄 들어가면 좋습니다.
아래 코드에는 제가 여백을 넣어놨어요. ㅎㅎ

- 제가 써둔 `주석`은 삭제하고 커밋해주시면 좋겠습니다!
제가 코드를 수정하고 남긴 주석은 설명을 돕기 위한 것이었기 때문에, 이해하셨다면 제 주석은 삭제하고, 오히려 솜의 스타일 대로 주석으로 살짝 메모를 남기는 식은 어떨까요~? 😄 

- `main.swift`에서 호출이 되는 메서드의 중요도가 제일 높기 때문에, 그 메서드를 파일의 제일 상단부로 올려주시는 게 좋습니다. ⬆️ 
저희가 만든 코드를 다른 개발자가 처음 본다고 생각해볼까요?
  - 일단 main.swift 를 보기 시작할텐데, 이때 `completePeperos()` 메서드를 처음 보게 되겠죠.
  - 그렇다면 이 메서드가 무슨 기능을 하는지 확인하기 위해 `MakePepero.swift` 파일을 열게 될텐데, 이때 가장 상단부에 메서드가 딱! 👀 눈에 들어온다면 센스있겠죠!
  - 이 메서드 내부엔 `makeNormalPePero`, `makeToppingPepero` 처럼, 또 모르는 메서드가 등장하죠? 근데 그 메서드들은 바로 아래에 예쁘게 나열되어 있기 때문에, 물 흐르듯이 메서드들을 파악할 수 있게 됩니다.
  - ✅ 이처럼 `코드의 정렬 순서`를 고민하실 땐 `"남들이 내 코드를 처음 봤을 때, 쉽게 이해하게 만들려면 어떻게 해야 할까? 🤔"` 생각해보면 좋습니다!! 👍🏻 

```suggestion
func compeletePeperos() {
    makeNormalPepero(bodyHeight: 10, choko: "***", stickHeight: 4) // 일반 빼빼로
    makeToppingPepero(bodyHeight: 12, choko: "***", sprinkle: "&", stickHeight: 4) // & 토핑 빼뺴로
    makeToppingPepero(bodyHeight: 12, choko: "***", sprinkle: "#", stickHeight: 4) // # 토핑 빼빼로
    makeNormalPepero(bodyHeight: 6, choko: "|0|", stickHeight: 4) // 누드 빼빼로
    makeToppingPepero(bodyHeight: 10, choko: "🟫", sprinkle: "⭐︎", stickHeight: 4) // 네모 빼빼로
}

func makeNormalPepero(bodyHeight: Int, choko: String, stickHeight: Int) {
    for _ in 1...bodyHeight {
        print(" ", choko, separator: "")
    }
    
    peperoStick(height: stickHeight)
}

func makeToppingPepero(bodyHeight: Int, choko: String, sprinkle: String, stickHeight: Int) {
    for _ in 1...bodyHeight/2 {
        print(sprinkle, choko, " ", "\n", " ", choko, sprinkle, separator: "")
    }
    
    peperoStick(height: stickHeight)
}

func peperoStick(height: Int) {
    for _ in 1...height {
        print(" | |")
    }
    
    print("========================") // 구분선
}
```

2022-04-19 03:46 UTC, Jager-yoo commented on README.md
> +![빼빼로_순서도](https://user-images.githubusercontent.com/94514250/163798464-405f8076-d009-4fbb-8c9d-df5b0500ebfe.png)
수정사항 있을 때 마다 `순서도` 챙겨주시는 점, 정말 좋습니다!! 💯

2022-04-19 04:08 UTC, Jager-yoo commented
> @Jager-yoo 어제 늦은 시간인데도 불구하고 컨플릭트 오류 해결 도와주셔서 다시 한 번 감사드립니다:) 아무래도 pull하면서 생겨난 컨플릭트 오류인 거 같아 기억을 거슬러 올라가보기 시작했어요.
> 
> * pull을 하면서 생겨났던 오류
>   Your local changes to the following files would be overwritten by merge -> [해당 해결방법](https://goddaehee.tistory.com/253) untracked working tree files overwritten -> [해당 해결방법](https://devonaws.com/git/git-pull-%EB%AA%85%EB%A0%B9-%EC%8B%9C%EC%97%90-untracked-working-tree-files-overwritten-%EB%82%98%EC%98%AC-%EB%95%8C/)
>   (혹시 이 부분에서 문제였을지도 모른다는 생각에 한 번 올려봅니다.)
> 
> 제 원격 저장소의 commit 기록이 다 날라갔던 상태라 해당 방법들로 pull 오류를 해결하고 제 브렌치에서 pull을 진행했죠! 현재 제 컴퓨터에 있던 Week 1 프로젝트의 파일에서는 _아이스크림 스위프트 파일, 빼빼로 스위프트 파일, 메인 스위프트 파일_ 이렇게 3개의 파일이 들어있었던 상태였습니다. 하지만 제가 pull해온 Week 1 프로젝트 파일에서는 메인 스위프트 파일(아이스크림 코드가 있는) 하나였죠.
> 
> 기존의 Week 1 프로젝트의 파일과 제 브렌치에서 pull해온 Week 1 프로젝트의 파일이 그렇게 충돌이 일어나 컨플릭트 오류가 생겨난 것 같습니다. 아무리 생각해도 이 방법 아니고서야... 이런 오류가 일어나지 않을 거 같아요.
> 
> 이런 상태로 git add를 통해 _아이스크림 스위프트 파일, 빼빼로 스위프트 파일, 메인 스위프트 파일_ 3개의 파일이 들어있는 파일만 .xcodeproj 파일을 포함하지 않은 채 따로 커밋을 진행했습니다.
> 
> 그래서 .xcodeproj 파일을 여셨을 때, 컨플릭트 오류와 함께 아이스크림 파일, 빼빼로 파일이 포함되지 않았던 이유였던 것 같습니다...
> 
> 제가 코딩 초보자라 어떻게 설명하면 좋을지... 이게 맞는지 잘 모르겠지만 제 생각을 예거에게 공유하고 싶었습니다!

솜!
문제 해결 이후 그 `원인`을 다시 생각해보셨군요! 아주~~ 좋습니다. 👏🏻👏🏻 
제가 어제 요런 말을 솜에게 드렸었죠.

`"컨플릭트는 보통 merge 할 때 발생한다."`
그리고 솜은 `git pull` 과정에서 컨플릭트가 발생한 것으로 분석하셨는데
재밌는 점은 ㅎㅎ git pull 과정은 사실 2개의 명령어가 합쳐진 것이라는 겁니다! 👍🏻 

`git pull = git fetch + git merge`
여기서 fetch 는 코드를 원격 레포(깃헙)에서 다운 받는 과정이고, 그 다운 받은 코드를, 현재 Local 코드와 merge 하는 거죠.
다른 개발자와 함께 작업을 할 때, 그 사람이 올린 커밋을 `git pull`하게 되면, 내 Xcode 에 자동으로 반영이 되는 모습을 보셨을 거에요. 😄 

아무튼, git pull 만으로도 충분히 컨플릭트가 날 수 있었던 상황 같고, 솜은 이 상황을 잘 분석해주셨습니다. 💯 
제가 찾은 링크 2개 정도 더 참고하면서 마무리하시면 좋겠습니다!
-

2022-04-21 07:41 UTC, jsa0224 reviewed
@Jager-yoo

조언해주신 부분 반영해서 수정했습니다.
코드가 제대로 돌아가는 것에만 초점을 맞춰서 상대방 시점을 전혀 생각하지 못 했어요! 🙀
좋은 지적 감사드립니다 👍

2022-04-21 08:10 UTC, Jager-yoo commented on CodeStarterCamp_Week1/MakePepero.swift
> +    makeToppingPepero(bodyHeight: 10, choko: "🟫", sprinkle: "⭐︎", stickHeight: 4) // 네모 빼빼로
ㅎㅎㅎ수고하셨습니다!
머지하겠습니다. `Week2` 도 화이팅입니다! 🎉

2022-04-21 08:10 UTC, merged