Week [step3] duck
yagom-academy/swift_starter-week1 pull request #91
Opened 2022-04-18 11:43 UTC by Hong-seungju

@llghdud921  안녕하세요 제리 Step3 입니다.

2022-04-18 14:04 UTC, llghdud921 requested changes
안녕하세요 duck
이번주도 같이 으쌰으쌰해봅시다!!!

### Good
- 순서도를 잘 작성해주셨어요 👍  다만 한가지 말씀드릴점은 실행되는 함수에 Yes, No를 붙여주셨는데 함수가 실행되지 않은 경우는 해당 코드상에는 없어서 화살표만 작성해주셔도 될 것 같습니다 !!

### 조언드릴 부분
- 요구사항에 총 네가지 함수를 만들어 코드를 작성하라고 나와있는데 `각종 매개변수를 받아 위의 세 메서드를 호출하는 함수` <- 요 함수가 빠진 것 같아요! 그래서 peperoBody라는 전역변수도 생기게 된 것 같습니다... 개선해보아요~
- 코드에 작성해주신 예제는 잘 출력이 되지만 다른 예제를 실행해보면 요구사항과 다릅니다 👀
그리고 실행 예시의 정보(길이, 몸통, 토핑, 막대길이) 또한 출력되고 있지 않네용..
실행 결과 👇
<img width="499" alt="스크린샷 2022-04-18 오후 10 51 00" src="https://user-images.githubusercontent.com/40068674/163817873-1814f528-a399-4d52-a5f5-4fb1b8ea9ddc.png">

실행예시와 달라서 우선은 네이밍과 코딩컨벤션 위주로 리뷰드렸습니다 😸
확인해주시고 궁금하신 점 있으시면 DM주세요~~

2022-04-18 23:12 UTC, Hong-seungju commented on CodeStarterCamp_Week1/pepero_making.swift
> +func makePeperoHeigth (peperoHeight: Int) {
넵 수정하고 다시 올리겠습니다.!!

2022-04-18 23:12 UTC, Hong-seungju commented on CodeStarterCamp_Week1/pepero_making.swift
> +    }
넵 다시 수정하겠습니다.!!

2022-04-18 23:13 UTC, Hong-seungju commented on CodeStarterCamp_Week1/pepero_making.swift
> +func makePepero (peperoMatiral: String, topping: String) {
오타입니다.... 다시 수정해서 올리겠습니다.

2022-04-19 11:29 UTC, Hong-seungju commented
@llghdud921  Step3 수정본입니다. 
요구사항을 제대로 이해하지 못했습니다.ㅠ
순서도 또한 수정하여 올립니다.

2022-04-20 15:51 UTC, llghdud921 requested changes
안녕하세요! duck
우선 늦게 피드백드려서 정말 죄송하고.. 이해해주셔서 감사드립니다🙇‍♀️

그리고 코멘트를 남겨놓았는데 
저는 duck이 이번 스텝에서 네이밍을 마스터하고 넘어가기를 바라고있어요!
변수명, 함수명을 잘 짓는 이유는 코드는 혼자 짜는 것이 아니기 때문이죠🤣 다른 사람이 duck의 코드를 보았을 때 정확히 이해하고 파악해야하고 심지어 몇년뒤에 duck 자신이 짠 코드를 보아도 못알아볼수도 잇어요ㅎㅎ
함수명은 어떤 기능을 하는지, 변수명은 어떤 단어를 나타내는지에 맞추어 네이밍을 다시 개선해보도록 합시다 🙌

2022-04-20 15:51 UTC, llghdud921 commented on CodeStarterCamp_Week1/pepero_making.swift
> +func peperoMake(peperoHeight: Int, pepero: String, topping: String, peperoBar: Int) {
다른 함수의 경우 `makePeperoBoby`와 같이 동사구로 네이밍해주셨는데 해당 함수만 `peperoMake`네요!
혹시 이유가 있으시면 어떤 이유로 해당 네이밍을 하셨는지 궁금합니다!

2022-04-20 15:51 UTC, llghdud921 commented on CodeStarterCamp_Week1/pepero_making.swift
> +    print("막대길이: \(peperoBar)")
전반적으로 함수명은 잘 지어주셨는데 파라미터 변수 네이밍과 print문에 나타나있는 단어와 일치하지 않는 것 같습니다 🥲

- 앞서 `peperoMake`에 `pepero`를 만든다고 나타내 있으니 길이의 경우 `bodyHeight`로만 나타내어도 충분히 명확할 것 같아요 :)
- 몸통을 `bodyContent`와 같은 네이밍으로 개선해볼 수 있을 것 같습니다
- 막대길이 또한 `peperoBar`보다는 `barHeight`로 더 명확하게 변수를 나타낼 수 있을 것 같아요!

2022-04-20 15:51 UTC, llghdud921 commented on CodeStarterCamp_Week1/pepero_making.swift
> +peperoMake(peperoHeight: 6, pepero: "|✌|", topping: "", peperoBar: 2)
나만의 빼빼로 만들어보기!! 정말 좋습니다 👍 👍

2022-04-20 22:08 UTC, Hong-seungju commented on CodeStarterCamp_Week1/pepero_making.swift
> +func peperoMake(peperoHeight: Int, pepero: String, topping: String, peperoBar: Int) {
빼빼로만들 모든 매개변수가 이 함수에 사용되어 peperoMake라고 함수명을 네이밍 하였습니다.

2022-04-20 22:10 UTC, Hong-seungju commented on CodeStarterCamp_Week1/pepero_making.swift
> +    print("막대길이: \(peperoBar)")
넵 알겠습니다. 
더 간단명료하게 변수 네이밍이 된거 같아요

2022-04-21 00:00 UTC, Hong-seungju commented
@llghdud921 안녕하세요 제리
뺴뱨로 만들기 네이밍수정 입니다.
더 명확하게 네이밍을 짓는 방법에 대해서 고민하겠습니다.

2022-04-21 05:11 UTC, llghdud921 approved these changes
네 리팩토링 해주신거 잘 확인했습니다!!
머지하도록 하고 week2로 넘어가시죠!! 화이팅입니다 👍 

> 빼빼로만들 모든 매개변수가 이 함수에 사용되어 peperoMake라고 함수명을 네이밍 하였습니다.

이 부분은 side effect이 있는 함수로 동사구로 짓기를 API Design Guidelines에서 권장하고 있는데요!
일반적으로 동사가 앞에 옵니다! 예를들어 `makePepero` 이렇게요!
다음 코드 작성하실때 참고해주세요~!!

2022-04-21 05:11 UTC, merged