week1 [STEP2] sonshinwoo
yagom-academy/swift_starter-week1 pull request #95
Opened 2022-04-19 02:02 UTC by Sonshinwoo

STEP2 내용입니다.

저번에 step1때 모르고 같이 올려서 다시 재업로드 합니다.

2022-04-19 02:07 UTC, Sonshinwoo commented
@yeahg-dev 

STEP2 내용입니다.

저번에 step1때 모르고 같이 올려서 다시 재업로드 합니다.

2022-04-19 08:56 UTC, yeahg-dev commented
안녕하세요 신우님!

반복문을 사용해서 잘 구현해주셨습니다!👏🏻👏🏻
함수 네이밍도 고민을 많이 흔적이 보이네요!
스텝2도 수고 많으셨습니다~!

다만 이전 스텝1 PR에서 STEP2 코드를 작성한 커밋이 머지가되어서,
현재 이 PR에서 해당 코드에 대한 리뷰가 어려워요😰
그래서 신우님 브랜치의 커밋에 코멘트 달아두었으니 [리뷰](https://github.com/Sonshinwoo/swift_starter-week1/commit/d359a84da72adabb5843d5fcdd0a995bb7a5db7c)에서 확인해주시고, 코멘트 남겨주세요!

추가적으로 현재 main.swift가 Xcode 프로젝트가 아닌 CodeStarterCamp_Week1 파일에 따로 생성해주셨어요.
아래 요구사항에 따라 main.swift파일을 생성해주세요!
>- Clone 받은 폴더 내부에 Xcode 프로젝트를 생성합니다.
    - (MacOS 항목의 Command-Line-Tool을 선택해주세요.)
 
[리뷰](https://github.com/Sonshinwoo/swift_starter-week1/commit/d359a84da72adabb5843d5fcdd0a995bb7a5db7c)의 커멘트와 위 요구사항 수정 후 재리뷰 요청 주세요.
커멘트에 대한 궁금증이나 질문은 언제든 편하게 디엠 주세요😊

2022-04-20 04:05 UTC, Sonshinwoo commented
@yeahg-dev 
말씀 해주신 내용 전부 수정 했습니다. 
1.  폴더 생성
기존에 코드를 썼던 code startcamp_week1 파일이 아닌 xcode에서 week1 이라는 폴더에 새로 코드를 작성 했습니다.
2.  스위프트 컨벤션
지적해 주셨던 띠어쓰기에 관한 부분을 스위프트 공식 문서에 맞춰 다시 작성했습니다. 
3. 카멜 케이스 생성
카멜케이스 사용방법에 대해 숙지하고 있다고 생각했는데 무의식적으로 몇개씩 오타가 나네요 ㅎㅎ 마지막 부분 수정했습니다

2022-04-20 05:35 UTC, yeahg-dev requested changes
코딩 컨벤션을 통일 해서 더 읽기 좋은 코드가 되었네요😀
폴더 생성과 카멜케이스도 잘 지켜주셨어요!

네이밍에 대한 리뷰 추가적으로 남겼습니다.
좀 더 공부하고 고민해보면 좋을 것 같습니다🙂

그리고 순서도에 대한 수정사항이 보이지 않네요. [순서도 관련 피드백](https://github.com/Sonshinwoo/swift_starter-week1/commit/d359a84da72adabb5843d5fcdd0a995bb7a5db7c#commitcomment-71587590)
다시 한번 확인 부탁드릴게요!

2022-04-20 05:35 UTC, yeahg-dev commented on week1/week1/main.swift
> +func makeIcecreamBody(cream: Int) {
아이스크림 몸통을 만드는 함수라는 걸 함수이름만 봐도 알 수있네요😃👍

2022-04-20 05:35 UTC, yeahg-dev commented on week1/week1/main.swift
> +func namooStick(stick: Int) {
이 함수는 이름을 바꿔주지 않은 이유가 있을까요??

2022-04-20 05:35 UTC, yeahg-dev commented on week1/week1/main.swift
> +makeIcecream(cream: 9, stick: 4)
`makeIceCream(cram:,stick)`, `makeIceCreamBody(cream:)`,`namooStick(stick:)` 3가지 함수 모두 [Swift API Guideline](https://www.swift.org/documentation/api-design-guidelines/#parameter-names)의 아래 규칙에 따라 수정해볼 수 있을 것 같아요
>" When the first argument forms part of a [prepositional phrase](https://en.wikipedia.org/wiki/Adpositional_phrase#Prepositional_phrases), give it an argument label." 

네이밍을 한번 더 고민해봅시다!

2022-04-21 06:04 UTC, Sonshinwoo commented
@yeahg-dev 

피드백 과 순서도에 관련한 내용 수정했습니다. 
항상 커밋할때 마다 이게 맞는건가...? 싶네요 ㅎㅎ; 

아 그리고 저번에 네이밍과 관련해서 피드백 해주신 부분에 대해 궁금한게 있는데요
"첫번째 인자가 전치사구에 포함될 때, 두번째 인자 등 추가적인 argument 역시 phrase에 포함되는 것이 아니라면 label을 한다."  라는 내용을 저는 인자에 전치사가  있으면 중복해서 여러 인자의 이름(ex: 인자1: makingicecream, makingstick--> making  이라는 분사 혹은 전치사)을 넣지말고 함수 부분에 기재(func makeIcecreamOf --> 동사+ 명사 + of) 하고 나머지 인자값이 명사 형식으로 들어가서 완정한 문장을 만들어라 라고 이해 했는데 이게 맞는건가요?

2022-04-21 08:25 UTC, yeahg-dev requested changes
훨씬 더 명확하고 이해하기 쉬운 코드가 되었네요!👍

순서도도 많은 발전이 있네요!
- 적절한 기호를 잘 선택해주셨습니다👍

다만, 현재 코드와 실행 흐름이 조금 다른 것 같아요.
예를 들면 신우님 순서도에 따르면 반복문내 코드를 다 실행하고 나서 "********"가 8번 출력이 되는데요.
실제 코드는 반복문내 코드가 실행 될 때마다 "********"가 출력되고 있습니다. 

좀 더 정확하게 흐름을 표현할 수 있는 순서도로 변경해볼까요??
- 순서도 내 함수 코드를 똑같이 쓰는 대신 문장으로 표현해보도록 수정부탁드립니다.
예시)
for _ in 1 ... hieght ❌ 
i가 height보다 작은가? 🆗

[예시-참고 블로그](https://www.memoengine.com/blog/for%20%EB%AC%B8%20%EC%88%9C%EC%84%9C%EB%8F%84%20-%20for%20%EB%AC%B8(for%20loop)%20%EC%88%9C%EC%84%9C%EB%8F%84(flowchart)/)나 "반복문 순서도"와 같은 키워드로 순서도의 일반적인 작성 방법에 익숙해지시고,
손으로 종이에 직접 한 번 그려보는 걸 추천드립니다. 

추가적으로 좀 더 말씀을 드리자면, 
순서도는 코드에 대해 다른 사람과 소통할 수 있는 도구로서 쓰일 수도 있습니다.
따라서 일반적인 규칙은 따라주는 것이 좋습니다. (이건 마치, 글을 읽다가 맞춤법이 틀린게 보이면 조금 불편한 기분과 같달까요??) 
그래서 화살표의 양끝이 기호에서 떨어져있는 것은 수정하면 좋을 것 같습니다.

순서도 한 번 더 수정해보고 재리뷰 요청 주세요!
화이팅😃

2022-04-21 08:25 UTC, yeahg-dev commented on week1/week1/main.swift
> +func makeIcecreamOf(bodyheight:Int, stickheight: Int) {
가이드라인에 따라 잘 수정해주셨네요~!
함수가 문장처럼 자연스럽게 읽힙니다👍
Veryyyy goooood💯

2022-04-21 08:25 UTC, yeahg-dev commented on week1/week1/main.swift
> +    makeIcecreamBody(height: bodyheight)
여기서는 전치사 of를 따로 사용해주시진 않으셨네요.
`makeIceCreamOf`가 내포하는 의미와 `makeIceCreamBody`가 내포하는 의미가 비슷한데
네이밍 규칙이 좀 다르면 혼란스러울 수 있을 것 같습니다.

이에 대한 신우님 생각은 어떤가요?

2022-04-22 10:50 UTC, Sonshinwoo commented on week1/week1/main.swift
> +    makeIcecreamBody(height: bodyheight)
아이고 또 깜빡했네요 ㅎ;; 다시 수정하고 커밋하겠습니다!

아 릴리님 네이밍 관련해서 궁금한게 생겼는데 질문 하나만 해도될까요??
함수를 사용할 때 컨벤션이 있는것 처럼  피드백 해주신 코딩 처럼 함수간의 매개변수가 연결되어 있으면  네이밍을 할 때  규칙같은게 있나요???
예를들어 지금 makeicecreamof 의 매개변수는 bodyheight로 설정했고 makeicecreambody는 매개변수가 height 로  설정했는데  이 두 매개변수의 네이밍을 같게 만들거나 서로 비슷하게 만들어야 되는? 그런 규칙들이 혹시 있나요?

2022-04-22 10:55 UTC, Sonshinwoo commented
@yeahg-dev 
피드백 관련 내용 다시 수정하고 커밋 했습니다 ㅎ

2022-04-25 06:06 UTC, yeahg-dev commented on week1/week1/main.swift
> +    makeIcecreamBody(height: bodyheight)
Swift API가이드라인에서 그러한 규칙은 따로 명시되어 있지 않지만, 저의 개인적인 생각은 이렇습니다.
아이스크림 몸통을 만드는데 얼만큼의 높이를 정하는 상황`makeIceCreamBody`에서는 `height`만으로 의미가 충분히 전달이된다고 생각해요. 
그런데 아이스크림을 만드는데 몸통부분을 얼만큼의 높이를 정하는 상황`makeIceCreamOf`이라면 그냥 `height`라고만 하면 아이스크림의 몸통의 높이인지 스틱의 높이인지 구분할 수가 없겠죠? 그래서 저도 네이밍을 한다면 신우님과 동일하게 가져갔을 것 같습니다.

동일한 역할을 하는 파라미터라면 최대한 이름을 맞춰주는 것이 좋을 것 같구요, `makeIceCreamOf`과 같이 상황에 대한 정보가 충분하지 않은 경우에는 의미를 추가해서 네이밍할 것 같아요!

2022-04-25 06:10 UTC, yeahg-dev approved these changes

2022-04-25 06:10 UTC, merged

2022-04-25 06:15 UTC, yeahg-dev commented
네이밍에 대한 고민도 충분히 잘 해주셨고,
순서도도 코드의 흐름과 동일하게 작성 해주셨습니다.💯
(`끝`에 대한 기호만 다른 기호로 한번만 고민해봐주시고 다음 스텝에서 한 번 반영해보세요)

추가적으로 커밋하실 때 메시지를 뭐라고 써야할지 고민이 되신다면
아래 키워드를 공부해보셔도 좋을 것 같습니다!
- 카르마 스타일
- https://djkeh.github.io/articles/How-to-write-a-git-commit-message-kor/

step2 수고 많으셨고, step3에서 만나요!