Week 1 [STEP 2] Jay Lee
yagom-academy/swift_starter-week1 pull request #98
Opened 2022-04-19 12:49 UTC by jay0614-lee

@oksunwoo 
STEP 2 PR 보내드립니다!

### 코드를 작성하면서 알게된 점
- 사용하지 않는 변수는 _ 으로 대체해서 쓸 수 있다는 걸 알게 되었습니다. Xcode 에서 주의 메세지가 나타나서 수정하였습니다.

### 진행하면서 궁금했던 점
- 순서도에서 변수를 작성할 때, 어떤 값이 들어갈지 모르는 상태이기 때문에 숫자(값) 대신 함수 작성할 때 처럼 자료형을 넣었는데 이렇게 작성하여도 괜찮은지 알고 싶습니다. 

Git 과 Github 사용하는데 아직 헤매고 있어서 어째 과제보다 Commit & Push 를 진행하고 PR 작성하는게 더 어렵네요 ㅠㅠ
하루빨리 익숙해질 수 있도록 더 열심히 하겠습니다!

감사합니다!

2022-04-20 08:59 UTC, oksunwoo requested changes
함수 두개 작성하시고 출력까지 정상적으로 되는 것을 확인할 수 있었습니다.
다만 순서도를 확인할 수가 없는데, 이미지 파일로 변환해서 올려주시면 감사하겠습니다
그리고 커밋메시지로 보아 유추하건데, 순서도는 한 파일내에 작성해주셔야 코드의 흐름을 파악할 수 있기에 한 파일에서 수정해서 다시 업로드해주시면 될 것 같습니다

2022-04-20 08:59 UTC, oksunwoo commented on CodeStarterCamp_Week1/main.swift
> +func makeIceCream (line: Int) {
parameter 명이 line 보다는 아이스크림의 높이 또는 길이를 뜻하는 이름이 되면 더 좋을 것 같네요!

2022-04-20 08:59 UTC, oksunwoo commented on CodeStarterCamp_Week1/main.swift
> +
다른 부분과 달리 이 부분은 공백이 두줄인데 혹시 제이님만의 컨벤션이 있으신가요?

2022-04-20 14:17 UTC, jay0614-lee commented on CodeStarterCamp_Week1/main.swift
> +func makeIceCream (line: Int) {
의미에 맞게 높이를 뜻하는 height 로 수정하였습니다!

2022-04-20 14:19 UTC, jay0614-lee commented on CodeStarterCamp_Week1/main.swift
> +
특별한 이유가 있지 않습니다. 작성하다가 두 줄이 띄어진걸 못보고 지나친 것 같습니다. 한 줄로 수정하였습니다!

2022-04-20 15:17 UTC, oksunwoo requested changes
현재 첨부해주신 순서도는 각각 메서드에 대한 순서도네요! 아주 논리적으로 잘 짜져있는데요
헌데 제이님의 순서도를 보고는 해당 프로그램이 어떻게 동작하는지 알 수 있는 방법이 없네요
저희는 프로그램에 대한 순서도를 작성해야하니 한번 흐름대로 작성을 해볼까요?
어떤 순서대로, 어떤 방식으로 코드가 짜여졌는지 생각해보면 좋을 것 같아요!

그리고 순서도를 다음과 같은 방식으로 짜면 좋을 것 같아요. 문법영향 없이 논리적인 흐름을 만들어내기 위함입니다. 현재는 변수의 선언부분만 고치면 되겠죠? 게다가 line이라는 것을 더 이상 사용하고 있지않잖아요!
```swift
(잘못된 예)
if person.name == "yagom"
 
(옳은 예)
person의 이름이 yagom인가?
```
수정 후 DM 주세요~

2022-04-21 04:49 UTC, jay0614-lee commented
@oksunwoo 
말씀해주신 내용 참고하여 순서도 수정해보았습니다.
확인 부탁드립니다!

2022-04-21 06:46 UTC, oksunwoo requested changes
DM 드렸습니다! 확인해보시고 수정부탁드립니다!

2022-04-21 07:23 UTC, jay0614-lee commented
@oksunwoo 
보내주신 내용 반영하여 수정하였습니다.
확인 부탁드립니다!

2022-04-21 08:53 UTC, merged